(ns ckway.bridge
  "Bridge classes: how generated code calls a JVM member that Clojure's compiler cannot call.

  Clojure's compiler munges every method name in a `.` form (`-` becomes `_`), so it cannot
  call `next-yIzh284` or `box-impl`. It also cannot call a non-public member (Kotlin hides some
  `inline` functions this way). A bridge is a small class with ONE public static method `call`
  that calls the target. The bridge name has only characters that Clojure keeps.

  A second use of the same storage (step 7): `reify-class`, the class of a `kt/reify` form. Kind `R`.

  Contract (step 5 adds a second kind of bridge and uses the same naming and storage):

    target  = {:kind :static|:virtual  :class \"fx.Uid\"  :name \"box-impl\"  :desc \"(J)Lfx/Uid;\"}
    (needed? target)       does a direct `.` form fail? (name is not Clojure-safe, or the member is not public)
    (bridge-class target)  => \"ckway.bridge.C_fx_Uid__box_impl__<hash>\"; the class exists after the call.
                           `call` has the descriptor of the target; for :virtual the receiver is
                           a first parameter of the target class. The expansion is
                           (. ckway.bridge.C_... (call args...)), a direct call without reflection.

  Naming (`class-name`): ckway.bridge.<kind>_<readable>__<hash>. The kind is one letter (`C` for a
  call bridge). The hash is the first 10 hex digits of SHA-1 over generator version, kind and the
  identity string of the bridge, so the same target always gives the same name, in every run.

  Storage (`install!`): the class is defined in memory (a DynamicClassLoader, so every Clojure
  loader finds it by name) unless a class of that name already exists (idempotent), and when
  `*compile-files*` is true the bytes are also written to `<*compile-path*>/ckway/bridge/<name>.class`
  every time. AOT-compiled code refers to the bridge class by name, so it needs the class file on
  the class path, and nothing of this namespace's generator.

  The generator (`ckway.bridge.gen`, uses `clojure.asm`) is loaded only when a bridge is created. Code
  that was AOT-compiled with its bridges runs without loading it.

  Kotlin bridges (kind `K`, DESIGN-2 rule 5): the bridge of a reified call is a Kotlin class that the
  Kotlin compiler makes from generated source (`ckway.bridge.ksrc`, `ckway.bridge.kotlinc`).
  `(kotlin-bridge-class spec)` => the Class, in this order:
    1. already defined in this JVM, or (outside AOT) a class of that name on the class path;
    2. the disk cache: directory `.ckway-cache/` under the working directory, or the system property
       `ckway.cache.dir` (an empty value turns the cache off). One entry is `<name>.class`, its inner
       classes `<name>$...class`, and `<name>.key`. The key is a SHA-1 over: bridge generator version,
       Kotlin version, JVM target, the source text, and for every class the call depends on (the class of
       the declaration, the class of a companion's outer class, the classes of the type arguments) the
       SHA-1 of its class file bytes plus, for a class in a jar, the size and modification time of the jar
       (the bytes of the class are not enough: an inline function of a multi-file facade lives in a part
       class of the same jar). A changed key is a miss: the bridge is compiled again and the entry replaced;
    3. the Kotlin compiler (the `:kotlinc` alias): a compile error becomes a kt error, a missing
       compiler a kt error that names the alias.
  Under AOT (`*compile-files*`) the classes are also written to `*compile-path*`, so a fresh JVM runs the
  compiled code with neither the compiler nor the generator. `kotlin-stats` counts what happened."
  (:require [clojure.java.io :as io]
            [clojure.string :as str])
  (:import [clojure.lang DynamicClassLoader RT Compiler]
           [java.lang.reflect Method Modifier]
           [java.lang.invoke MethodType]
           [java.security MessageDigest]))

(set! *warn-on-reflection* true)

(def ^:private generator-version
  "Part of every bridge name. Raise it when the generated bytecode changes."
  2)

(def package "ckway.bridge")

;; ---------------------------------------------------------------- naming

(defn- hex-hash [^String s]
  (let [d (.digest (MessageDigest/getInstance "SHA-1") (.getBytes s "UTF-8"))]
    (subs (apply str (map #(format "%02x" (bit-and 0xff %)) d)) 0 10)))

(defn- safe-part [s] (str/replace (str s) #"[^A-Za-z0-9]+" "_"))

(defn class-name
  "Deterministic binary class name of a bridge: kind (one letter), a readable part and the
  identity string that makes the name unique."
  [kind readable identity]
  (str package "." kind "_" (safe-part readable) "__" (hex-hash (str generator-version "|" kind "|" identity))))

(defn call-class-name [{:keys [kind class name desc]}]
  (class-name "C" (str class "_" name) (str (clojure.core/name kind) "|" class "|" name "|" desc)))

;; ---------------------------------------------------------------- need

(defn- load-class ^Class [^String n]
  (try (Class/forName n false (RT/baseLoader))
       (catch ClassNotFoundException _ nil)
       (catch LinkageError _ nil)))

(defn- descriptor ^String [^Method m]
  (.toMethodDescriptorString (MethodType/methodType (.getReturnType m) (.getParameterTypes m))))

(defn target-method
  "The reflective method of a target, or nil."
  ^Method [{:keys [class name desc]}]
  (when-let [c (load-class class)]
    (first (filter (fn [^Method m] (and (= name (.getName m)) (= desc (descriptor m)))) (.getDeclaredMethods ^Class c)))))

(defn public?
  "Is the target method callable from another package (public method of a public class)?"
  [target]
  (if-let [m (target-method target)]
    (and (Modifier/isPublic (.getModifiers m)) (Modifier/isPublic (.getModifiers (.getDeclaringClass m))))
    true))

(defn clojure-name? [^String n] (= n (Compiler/munge n)))

(defn needed?
  "Can a direct `.` form not call the target? True for a name that Clojure munges and for a
  member that is not public."
  [{:keys [name] :as target}]
  (boolean (or (not (clojure-name? name)) (not (public? target)))))

;; ---------------------------------------------------------------- storage

(def ^:private installed
  "Documented cache: class name -> Class, defined by `install!` in this JVM (keeps them reachable)."
  (atom {}))

(defn class-file
  "File of the class `cname` under the compile path."
  ^java.io.File [^String cname]
  (io/file *compile-path* (str (str/replace cname "." "/") ".class")))

(defn install!
  "Make the class `cname` (bytes `bs`) available: define it in memory unless a class of that name
  exists, and write it under `*compile-path*` when `*compile-files*` is true. => the Class."
  ^Class [^String cname ^bytes bs]
  (when *compile-files*
    (let [f (class-file cname)]
      (io/make-parents f)
      (with-open [o (io/output-stream f)] (.write o bs))))
  (locking installed
    (or (get @installed cname)
        (let [c (or (load-class cname)
                    (.defineClass (DynamicClassLoader. (RT/baseLoader)) cname bs nil))]
          (swap! installed assoc cname c)
          c))))

;; ---------------------------------------------------------------- bridges

(defn bridge-class
  "Name of the call bridge class for `target`; creates and installs it if necessary."
  [target]
  (let [cname (call-class-name target)
        access (if (public? target) :public :private)]
    (when (or *compile-files* (not (contains? @installed cname)))
      (let [gen (requiring-resolve 'ckway.bridge.gen/call-bridge-bytes)]
        (install! cname (gen cname (assoc target :access access)))))
    cname))

(defn reify-class
  "Name of the class of a `kt/reify` form (kind `R`, DESIGN-2 rule 10): it implements the interfaces of
  `spec` ({:ifaces [binary names] :methods [...]}, see `ckway.bridge.gen/reify-class-bytes`) with methods that
  call Clojure functions. Same storage as a call bridge (`install!`), so a namespace that is AOT-compiled
  carries the class and runs without the generator. `readable` is for the class name only."
  [readable spec]
  (let [cname (class-name "R" readable (pr-str spec))]
    (when (or *compile-files* (not (contains? @installed cname)))
      (let [gen (requiring-resolve 'ckway.bridge.gen/reify-class-bytes)]
        (install! cname (gen cname spec))))
    cname))

;; ---------------------------------------------------------------- Kotlin bridges

(def kotlin-stats
  "Counters of the Kotlin bridges of this JVM: :compiled (the Kotlin compiler ran), :cache-hits (made from
  the disk cache), :compile-ms (a vector, one per compilation), :cache-ms (one per cache hit)."
  (atom {:compiled 0 :cache-hits 0 :compile-ms [] :cache-ms []}))

(def ^:private kotlin-bytes
  "Documented cache: Kotlin bridge class name -> {binary-name bytes} (to write under AOT again)."
  (atom {}))

(defn cache-dir
  "The disk cache directory of the Kotlin bridges, or nil when it is turned off."
  ^java.io.File []
  (let [p (System/getProperty "ckway.cache.dir")]
    (cond (nil? p) (io/file (System/getProperty "user.dir") ".ckway-cache")
          (str/blank? p) nil
          :else (io/file p))))

(defn- sha1-hex [^bytes bs]
  (apply str (map #(format "%02x" (bit-and 0xff %)) (.digest (MessageDigest/getInstance "SHA-1") bs))))

(defn- stamp-of
  "Stamp of the class `binary`: SHA-1 of its class file, and the size and time of its jar."
  [^String binary]
  (if-let [^java.net.URL u (.getResource (RT/baseLoader) (str (str/replace binary "." "/") ".class"))]
    (let [bs (with-open [in (.openStream u)] (.readAllBytes in))
          jar (when (= "jar" (.getProtocol u))
                (let [p (.getPath u)] (io/file (java.net.URI. (subs p 0 (.indexOf p "!"))))))]
      (str binary ":" (sha1-hex bs) (when jar (str "@" (.length ^java.io.File jar) "/" (.lastModified ^java.io.File jar)))))
    (str binary ":absent")))

(defn- cache-key [source stamp-classes]
  (sha1-hex (.getBytes (str/join "\n" (concat [(str "ckway-kotlin-bridge-v2") (str kotlin.KotlinVersion/CURRENT)
                                               (or (System/getProperty "ckway.jvm-target") (str (.feature (Runtime/version))))
                                               source]
                                              (map stamp-of stamp-classes)))
                            "UTF-8")))

(defn- read-cache
  "{binary bytes} from the cache entry `cname` when its key is `key`, else nil."
  [^java.io.File dir cname key]
  (let [kf (io/file dir (str cname ".key"))]
    (when (and (.isFile kf) (= key (str/trim (slurp kf))))
      (let [files (filter (fn [^java.io.File f] (let [n (.getName f)]
                                                  (and (str/ends-with? n ".class")
                                                       (or (= n (str cname ".class")) (str/starts-with? n (str cname "$"))))))
                          (.listFiles dir))]
        (when (some #(= (str cname ".class") (.getName ^java.io.File %)) files)
          (into {} (for [^java.io.File f files :let [n (.getName f)]]
                     [(subs n 0 (- (count n) 6)) (java.nio.file.Files/readAllBytes (.toPath f))])))))))

(defn- write-cache [^java.io.File dir cname key classes]
  (try
    (.mkdirs dir)
    (doseq [^java.io.File f (.listFiles dir) :let [n (.getName f)]
            :when (and (str/starts-with? n (str cname "$")) (str/ends-with? n ".class"))]
      (.delete f))
    (doseq [[n bs] classes]
      (with-open [o (io/output-stream (io/file dir (str n ".class")))] (.write o ^bytes bs)))
    (spit (io/file dir (str cname ".key")) key)
    (catch Exception _ nil)))

(defn- define-all!
  "Install the classes of one Kotlin bridge, all in ONE class loader (the classes of a `suspend` bridge
  reach each other as package-private members, which different loaders do not allow). The main class
  first. Under AOT the class files are written too. => the main Class."
  [cname classes]
  (when *compile-files*
    (doseq [[n bs] classes]
      (let [f (class-file n)]
        (io/make-parents f)
        (with-open [o (io/output-stream f)] (.write o ^bytes bs)))))
  (locking installed
    (or (get @installed cname)
        (let [loader (DynamicClassLoader. (RT/baseLoader))
              main (or (load-class cname) (.defineClass loader cname ^bytes (get classes cname) nil))]
          (doseq [[n bs] classes :when (and (not= n cname) (not (load-class n)))]
            (.defineClass loader n ^bytes bs nil))
          (swap! installed assoc cname main)
          (swap! kotlin-bytes assoc cname classes)
          main))))

(defn kotlin-bridge-class
  "The Class of the Kotlin bridge described by `spec` {:readable :identity :source (fn [cname] text)
  :stamp-classes [binary ...] :what text-for-errors}. See the namespace docstring."
  ^Class [{:keys [readable identity source stamp-classes what]}]
  (let [cname (class-name "K" readable identity)]
    (cond
      (and (not *compile-files*) (get @installed cname)) (get @installed cname)
      (and (not *compile-files*) (load-class cname)) (load-class cname)
      (and *compile-files* (get @kotlin-bytes cname))
      (define-all! cname (get @kotlin-bytes cname))
      :else
      (let [text (source cname)
            key (cache-key text stamp-classes)
            dir (cache-dir)
            t0 (System/nanoTime)
            cached (when dir (read-cache dir cname key))]
        (if cached
          (do (swap! kotlin-stats #(-> % (update :cache-hits inc) (update :cache-ms conj (/ (- (System/nanoTime) t0) 1e6))))
              (define-all! cname cached))
          (let [compile-source (requiring-resolve 'ckway.bridge.kotlinc/compile-source)
                r (try (compile-source what (str (subs cname (inc (.lastIndexOf ^String cname "."))) ".kt") text)
                       (catch clojure.lang.ExceptionInfo e
                         (throw (if (:kt/compile-failed (ex-data e))
                                  (ex-info (ex-message e) (assoc (ex-data e) :kt/bridge-source text) e)
                                  e))))]
            (swap! kotlin-stats #(-> % (update :compiled inc) (update :compile-ms conj (:ms r))))
            (when dir (write-cache dir cname key (:classes r)))
            (define-all! cname (:classes r))))))))
