(ns ckway.bridge
  "Bridge classes: how generated code calls a JVM member that Clojure's compiler cannot call.

  Clojure's compiler munges every method name in a `.` form (`-` becomes `_`), so it cannot
  call `next-yIzh284` or `box-impl`. It also cannot call a non-public member (Kotlin hides some
  `inline` functions this way). A bridge is a small class with ONE public static method `call`
  that calls the target. The bridge name has only characters that Clojure keeps.

  A second use of the same storage: `reify-class`, the class of a `kt/reify` form. Kind `R`.

  Contract (the call bridge, kind `K`, and the `kt/reify` class, kind `R`, share the naming and the storage):

    target  = {:kind :static|:virtual  :class \"fx.Uid\"  :name \"box-impl\"  :desc \"(J)Lfx/Uid;\"}
    (needed? target)       does a direct `.` form fail? (name is not Clojure-safe, or the member is not public)
    (bridge-class target)  => \"ckway.bridge.C_fx_Uid__box_impl__<hash>\"; the class exists after the call.
                           `call` has the descriptor of the target; for :virtual the receiver is
                           a first parameter of the target class. The expansion is
                           (. ckway.bridge.C_... (call args...)), a direct call without reflection.

  Naming (`class-name`): ckway.bridge.<kind>_<readable>__<hash>. The kind is one letter (`C` for a
  call bridge). The hash is the first 10 hex digits of SHA-1 over generator version, kind and the
  identity string of the bridge, so the same target always gives the same name, in every run.

  Storage (`install!`): the class is defined in memory (a DynamicClassLoader, so every Clojure
  loader finds it by name) unless a class of that name already exists (idempotent), and when
  `*compile-files*` is true the bytes are also written to `<*compile-path*>/ckway/bridge/<name>.class`
  every time. AOT-compiled code refers to the bridge class by name, so it needs the class file on
  the class path, and nothing of this namespace's generator.

  The generator (`ckway.bridge.gen`, uses `clojure.asm`) is loaded only when a bridge is created. Code
  that was AOT-compiled with its bridges runs without loading it.

  Kotlin bridges (kind `K`, README rule 5): the bridge of a reified call is a Kotlin class that the
  Kotlin compiler makes from generated source (`ckway.bridge.ksrc`, `ckway.bridge.kotlinc`).
  `(kotlin-bridge-class spec)` => the Class, in this order:
    1. already defined in this JVM, or (outside AOT) a class of that name on the class path;
    2. the disk cache (`ckway.bridge.cache`): a per-user directory (`$XDG_CACHE_HOME/ckway`, `~/.cache/ckway`,
       `%LOCALAPPDATA%\\ckway`), or the system property `ckway.cache.dir` (an empty value turns the cache off).
       It is never read from the working directory. An entry stores a SHA-256 of every class file, and the
       bytes are verified before they are defined; an entry that fails is deleted and compiled again. The key
       is a SHA-256 over: bridge generator version, Kotlin stdlib version, JVM target, the source text, and for
       every class the call depends on (the class of the declaration AND the part classes of a multi-file
       facade, the class of a companion's outer class, the classes of the type arguments) the SHA-256 of
       its class file bytes plus, for a class in a jar, the size and modification time of the jar; and the
       version of the Kotlin compiler that made the entry. A changed key is a miss;
    3. the Kotlin compiler (the `:kotlinc` alias): a compile error becomes a kt error, a missing
       compiler a kt error that names the alias.
  Under AOT (`*compile-files*`) the classes are also written to `*compile-path*`, so a fresh JVM runs the
  compiled code with neither the compiler nor the generator. `kotlin-stats` counts what happened."
  (:require [clojure.java.io :as io]
            [clojure.string :as str]
            [ckway.bridge.cache :as cache])
  (:import [clojure.lang DynamicClassLoader RT Compiler]
           [java.lang.reflect Method Modifier]
           [java.lang.invoke MethodType]
           [java.security MessageDigest]))

(set! *warn-on-reflection* true)

(def ^:private generator-version
  "Part of every bridge name. Raise it when the generated bytecode changes."
  3)

(def package "ckway.bridge")

;; ---------------------------------------------------------------- naming

(defn- hex-hash [^String s]
  (let [d (.digest (MessageDigest/getInstance "SHA-1") (.getBytes s "UTF-8"))]
    (subs (apply str (map #(format "%02x" (bit-and 0xff %)) d)) 0 10)))

(defn- safe-part [s] (str/replace (str s) #"[^A-Za-z0-9]+" "_"))

(defn class-name
  "Deterministic binary class name of a bridge: kind (one letter), a readable part and the
  identity string that makes the name unique."
  [kind readable identity]
  (str package "." kind "_" (safe-part readable) "__" (hex-hash (str generator-version "|" kind "|" identity))))

(defn call-class-name [{:keys [kind class name desc]}]
  (class-name "C" (str class "_" name) (str (clojure.core/name kind) "|" class "|" name "|" desc)))

;; ---------------------------------------------------------------- need

(defn- load-class ^Class [^String n]
  (try (Class/forName n false (RT/baseLoader))
       (catch ClassNotFoundException _ nil)
       (catch LinkageError _ nil)))

(defn- descriptor ^String [^Method m]
  (.toMethodDescriptorString (MethodType/methodType (.getReturnType m) (.getParameterTypes m))))

(defn- not-found [msg]
  (ex-info msg {:kt/error true :kt/bridge-target-not-found true}))

(defn- declared [^Class c name desc]
  (first (filter (fn [^Method m] (and (= name (.getName m)) (= desc (descriptor m)))) (.getDeclaredMethods c))))

(defn- find-method
  "The method `name`/`desc` in `c`, its superclasses and then all its super-interfaces (a multi-file facade
  inherits its functions from the part classes, a class inherits default methods). Nearest first."
  ^Method [^Class c name desc]
  (or (loop [k c]
        (when k (or (declared k name desc) (recur (.getSuperclass k)))))
      (let [seen (volatile! #{})]
        (letfn [(walk [^Class k]
                  (when (and k (not (contains? @seen k)))
                    (vswap! seen conj k)
                    (or (declared k name desc)
                        (some walk (.getInterfaces k))
                        (walk (.getSuperclass k)))))]
          (walk c)))))

(defn target-method
  "The reflective method of a target (declared by the class or inherited, see `find-method`), or nil. The
  class of the target that does not exist is nil too; `resolve-target` is the checked version."
  ^Method [{:keys [class name desc]}]
  (when-let [c (load-class class)]
    (find-method c name desc)))

(defn resolve-target
  "{:method :declaring (Class) :public? bool :access :public|:private} of a target, or a `kt:` error that
  names the class, the member and the descriptor. `:declaring` is the class that declares the method: for an
  `@InlineOnly` function of a multi-file facade it is the (private) part class, not the facade."
  [{:keys [class name desc] :as target}]
  (let [c (load-class class)]
    (when-not c
      (throw (not-found (str "kt: the class " class " of the bridge target `" name desc "` is not on the class path"))))
    (let [m (find-method c name desc)]
      (when-not m
        (throw (not-found (str "kt: the member `" name "` with descriptor " desc " was not found in " class
                               " or in its superclasses and interfaces (a bridge needs it to make a call that Clojure cannot make)"))))
      (let [d (.getDeclaringClass m)
            pub? (and (Modifier/isPublic (.getModifiers m)) (Modifier/isPublic (.getModifiers d)))]
        {:method m :declaring d :public? pub? :access (if pub? :public :private)}))))

(defn public?
  "Is the target method callable from another package (public method of a public class)? A target that does not
  exist is a `kt:` error (see `resolve-target`)."
  [target]
  (:public? (resolve-target target)))

(defn clojure-name? [^String n] (= n (Compiler/munge n)))

(defn needed?
  "Can a direct `.` form not call the target? True for a name that Clojure munges and for a
  member that is not public. A target that is not found is a `kt:` error."
  [{:keys [name] :as target}]
  (boolean (or (not (clojure-name? name)) (not (public? target)))))

;; ---------------------------------------------------------------- canonical identity

(defn canon
  "A text of the data `x` that does not depend on any dynamic print variable (`*print-level*`, `*print-length*`,
  `*print-namespace-maps*`, `*print-meta*`...): containers are written here, maps and sets in sorted order,
  only scalars go through `pr-str`, with the print variables at their defaults."
  [x]
  (cond
    (map? x) (str "{" (str/join "," (sort (map (fn [[k v]] (str (canon k) " " (canon v))) x))) "}")
    (set? x) (str "#{" (str/join "," (sort (map canon x))) "}")
    (sequential? x) (str "[" (str/join "," (map canon x)) "]")
    (nil? x) "nil"
    (or (class? x) (string? x) (number? x) (keyword? x) (symbol? x) (boolean? x) (char? x))
    (binding [*print-length* nil *print-level* nil *print-meta* false *print-readably* true
              *print-dup* false *print-namespace-maps* false]
      (pr-str x))
    :else (str "<" (.getName (class x)) ">" x)))

;; ---------------------------------------------------------------- storage

(def ^:private installed
  "Documented cache: class name -> Class, defined by `install!` in this JVM (keeps them reachable). One entry
  per class name: a class that is replaced (a reloaded interface) drops the old one."
  (atom {}))

(defn class-file
  "File of the class `cname` under the compile path."
  ^java.io.File [^String cname]
  (io/file *compile-path* (str (str/replace cname "." "/") ".class")))

;; proxy-super cannot be type-hinted: the reflection it needs is on loadClass of a ClassLoader (a few calls per class)
(set! *warn-on-reflection* false)
(defn- loader-for
  "The class loader that defines a generated class. With `ifaces` (Classes) the names of those interfaces resolve
  to those very classes, not to whatever class of that name the parent loader chain finds first (a reloaded
  interface: the old class may still be loaded by a loader on the chain)."
  ^DynamicClassLoader [ifaces]
  (if (empty? ifaces)
    (DynamicClassLoader. (RT/baseLoader))
    (let [by-name (into {} (map (fn [^Class c] [(.getName c) c]) ifaces))]
      (proxy [DynamicClassLoader] [(RT/baseLoader)]
        (loadClass
          ([^String n] (or (get by-name n) (proxy-super loadClass n)))
          ([^String n r] (or (get by-name n) (proxy-super loadClass n r))))))))

(set! *warn-on-reflection* true)

(defn install!
  "Make the class `cname` (bytes `bs`) available: define it in memory unless a class of that name
  exists, and write it under `*compile-path*` when `*compile-files*` is true. => the Class.
  `ifaces` (Classes, optional): the class that exists is used only if it is assignable to all of them (it
  still implements the CURRENT interface classes); else a new one is defined and replaces it."
  (^Class [cname bs] (install! cname bs nil))
  (^Class [^String cname ^bytes bs ifaces]
   (when *compile-files*
     (let [f (class-file cname)]
       (io/make-parents f)
       (with-open [o (io/output-stream f)] (.write o bs))))
   (locking installed
     (let [ok? (fn [^Class c] (and c (every? (fn [^Class i] (.isAssignableFrom i c)) ifaces)))
           c (let [i (get @installed cname)]
               (if (ok? i)
                 i
                 (let [l (load-class cname)]
                   (if (ok? l) l (.defineClass (loader-for ifaces) cname bs nil)))))]
       (swap! installed assoc cname c)
       c))))

;; ---------------------------------------------------------------- bridges

(defn bridge-class
  "Name of the call bridge class for `target`; creates and installs it if necessary. The class is generated for
  the class that DECLARES the method (see `resolve-target`)."
  [target]
  (let [cname (call-class-name target)]
    (when (or *compile-files* (not (contains? @installed cname)))
      (let [{:keys [access declaring]} (resolve-target target)
            gen (requiring-resolve 'ckway.bridge.gen/call-bridge-bytes)]
        (install! cname (gen cname (assoc target :class (.getName ^Class declaring) :access access)))))
    cname))

(defn- stale?
  "Is the installed class of `cname` older than the interface classes `ifaces`?"
  [cname ifaces]
  (when-let [^Class c (get @installed cname)]
    (not (every? (fn [^Class i] (.isAssignableFrom i c)) ifaces))))

(def ^:private reify-generations
  "Base class name of a reify class -> number of the generation that is current (0: the plain name)."
  (atom {}))

(defn reify-class
  "Name of the class of a `kt/reify` form (kind `R`, README rule 10): it implements the interfaces of
  `spec` ({:ifaces [binary names] :methods [...]}, see `ckway.bridge.gen/reify-class-bytes`) with methods that
  call Clojure functions. Same storage as a call bridge (`install!`), so a namespace that is AOT-compiled
  carries the class and runs without the generator. `readable` is for the class name only.
  The identity is `canon` of the spec, so it does not depend on any print variable.
  `spec` may have `:iface-classes` (the Class objects of :ifaces; they are not part of the identity). The class is
  reused only while it implements those very classes. When an interface was redefined (the REPL, a reloaded
  Kotlin class) the old class implements the OLD interface, so a new class is defined under the name with
  the suffix `_g<n>` (a name cannot be defined again: class loaders find the old class of that name first) and
  the old class is dropped from the table, so it and its loader can be collected."
  [readable spec]
  (let [ifaces (or (:iface-classes spec) (keep load-class (:ifaces spec)))
        spec (dissoc spec :iface-classes)
        base (class-name "R" readable (canon spec))
        gen (requiring-resolve 'ckway.bridge.gen/reify-class-bytes)]
    (locking installed
      (let [n (get @reify-generations base 0)
            cname (if (zero? n) base (str base "_g" n))]
        (cond
          (and (not *compile-files*) (contains? @installed cname) (not (stale? cname ifaces))) cname
          (and (not *compile-files*) (contains? @installed cname))
          (let [c2 (str base "_g" (inc n))]
            (install! c2 (gen c2 spec) ifaces)
            (swap! installed dissoc cname)
            (swap! reify-generations assoc base (inc n))
            c2)
          :else (do (install! cname (gen cname spec) ifaces) cname))))))

;; ---------------------------------------------------------------- Kotlin bridges

(def kotlin-stats
  "Counters of the Kotlin bridges of this JVM: :compiled (the Kotlin compiler ran), :cache-hits (made from
  the disk cache), :compile-ms (a vector, one per compilation), :cache-ms (one per cache hit)."
  (atom {:compiled 0 :cache-hits 0 :compile-ms [] :cache-ms []}))

(def ^:private kotlin-bytes
  "Documented cache: Kotlin bridge class name -> {binary-name bytes} (to write under AOT again)."
  (atom {}))

(defn cache-dir
  "The disk cache directory of the Kotlin bridges, or nil when it is turned off (see `ckway.bridge.cache`)."
  ^java.io.File []
  (cache/dir))

(defn- class-bytes ^bytes [^String binary]
  (when-let [^java.net.URL u (.getResource (RT/baseLoader) (str (str/replace binary "." "/") ".class"))]
    (with-open [in (.openStream u)] (.readAllBytes in))))

(defn- major-version [^bytes bs] (+ (* 256 (bit-and 0xff (aget bs 6))) (bit-and 0xff (aget bs 7))))

(defn- parts-of
  "The part classes (binary names) of a Kotlin multi-file class facade (Metadata kind 4, d1 = the part
  names), else nil. The inline bodies of its functions are in the parts, not in the facade."
  [^String binary]
  (try
    (when-let [c (load-class binary)]
      (when-let [^kotlin.Metadata m (.getAnnotation ^Class c kotlin.Metadata)]
        (when (= 4 (.k m)) (map #(str/replace ^String % "/" ".") (.d1 m)))))
    (catch Throwable _ nil)))

(defn jvm-target
  "The Kotlin -jvm-target text for a bridge whose declaration is in the class `(first stamp-classes)`: the lowest
  target that can inline it = the class-file version of that class (and of the parts of a multi-file facade),
  at least 1.8, never above the running JVM. `-Dckway.jvm-target` overrides. Kotlin refuses to inline
  bytecode of a newer target into an older one, and a bridge of a newer class-file version than needed would
  fail with UnsupportedClassVersionError on an older JVM."
  [stamp-classes]
  (or (System/getProperty "ckway.jvm-target")
      (let [running (.feature (Runtime/version))
            owner (first stamp-classes)
            majors (when owner (keep #(some-> (class-bytes %) major-version) (cons owner (parts-of owner))))
            feature (if (seq majors) (- (long (apply max majors)) 44) running)
            f (max 8 (min feature running))]
        (if (= 8 f) "1.8" (str f)))))

(defn- stamp-one
  "Stamp of the class `binary`: SHA-256 of its class file, and the size and time of its jar."
  [^String binary]
  (if-let [^java.net.URL u (.getResource (RT/baseLoader) (str (str/replace binary "." "/") ".class"))]
    (let [bs (with-open [in (.openStream u)] (.readAllBytes in))
          jar (when (= "jar" (.getProtocol u))
                (let [p (.getPath u)] (io/file (java.net.URI. (subs p 0 (.indexOf p "!"))))))]
      (str binary ":" (cache/sha256-hex bs) (when jar (str "@" (.length ^java.io.File jar) "/" (.lastModified ^java.io.File jar)))))
    (str binary ":absent")))

(defn- stamp-of
  "Stamp of a class a bridge depends on: its own, and the stamps of the part classes when it is a multi-file facade."
  [^String binary]
  (let [parts (parts-of binary)]
    (str (stamp-one binary) (when (seq parts) (str "{" (str/join ";" (map stamp-one parts)) "}")))))

(defn- base-key
  "Everything the bridge depends on except the compiler (the compiler version is part of the entry name, see
  `ckway.bridge.cache`)."
  [source stamp-classes target]
  (cache/sha256-str (str/join "\n" (concat [(str "ckway-kotlin-bridge-v3") (str kotlin.KotlinVersion/CURRENT) target source]
                                           (map stamp-of stamp-classes)))))

(defn- link!
  "Force the verification and linking of the class `c`: a damaged class fails here, not in the first call."
  [^Class c]
  (Class/forName (.getName c) true (.getClassLoader c)))

(defn- define-all!
  "Install the classes of one Kotlin bridge, all in ONE class loader (the classes of a `suspend` bridge
  reach each other as package-private members, which different loaders do not allow). The main class
  first. Under AOT the class files are written too. All classes are linked before the bridge counts as
  installed (a LinkageError leaves nothing behind). `reuse?`: use a class of that name that already exists
  (on the class path). => the main Class."
  [cname classes reuse?]
  (when *compile-files*
    (doseq [[n bs] classes]
      (let [f (class-file n)]
        (io/make-parents f)
        (with-open [o (io/output-stream f)] (.write o ^bytes bs)))))
  (locking installed
    (or (get @installed cname)
        (let [loader (DynamicClassLoader. (RT/baseLoader))
              main (or (when reuse? (load-class cname)) (.defineClass loader cname ^bytes (get classes cname) nil))
              others (doall (for [[n bs] classes :when (and (not= n cname) (not (and reuse? (load-class n))))]
                              (.defineClass loader n ^bytes bs nil)))]
          (link! main)
          (doseq [c others] (link! c))
          (swap! installed assoc cname main)
          (swap! kotlin-bytes assoc cname classes)
          main))))

(def ^:private compile-lock
  "One Kotlin compilation at a time in this JVM, and one compilation per bridge: threads that need the same
  bridge wait and then find it installed."
  (Object.))

(defn kotlin-bridge-class
  "The Class of the Kotlin bridge described by `spec` {:readable :identity :source (fn [cname] text)
  :stamp-classes [binary ...] :what text-for-errors :before-compile (fn [])}. See the namespace docstring. The first of
  :stamp-classes is the class of the declaration (it decides the JVM target). `:before-compile` is called when the
  compiler is about to run (no stored bridge was found): it may throw."
  ^Class [{:keys [readable identity source stamp-classes what before-compile]}]
  (let [cname (class-name "K" readable identity)]
    (cond
      (and (not *compile-files*) (get @installed cname)) (get @installed cname)
      (and (not *compile-files*) (load-class cname)) (load-class cname)
      (and *compile-files* (get @kotlin-bytes cname))
      (define-all! cname (get @kotlin-bytes cname) true)
      :else
      (locking compile-lock
        (if (and (not *compile-files*) (get @installed cname))
          (get @installed cname)
          (let [text (source cname)
                target (jvm-target stamp-classes)
                base (base-key text stamp-classes target)
                dir (cache/dir)
                cv (cache/compiler-version)
                t0 (System/nanoTime)
                cached (when dir (cache/lookup dir cname base cv))
                hit (when cached
                      (try (let [c (define-all! cname cached false)]
                             (swap! kotlin-stats #(-> % (update :cache-hits inc) (update :cache-ms conj (/ (- (System/nanoTime) t0) 1e6))))
                             c)
                           (catch LinkageError e
                             (cache/debug "entry of " cname " cannot be defined or linked, deleted: " e)
                             (cache/discard! dir cname base cv)
                             nil)))]
            (or hit
                (let [_ (when before-compile (before-compile))
                      compile-source (requiring-resolve 'ckway.bridge.kotlinc/compile-source)
                      r (try (compile-source what (str (subs cname (inc (.lastIndexOf ^String cname "."))) ".kt") text {:jvm-target target})
                             (catch clojure.lang.ExceptionInfo e
                               (throw (if (:kt/compile-failed (ex-data e))
                                        (ex-info (ex-message e) (assoc (ex-data e) :kt/bridge-source text) e)
                                        e))))]
                  (swap! kotlin-stats #(-> % (update :compiled inc) (update :compile-ms conj (:ms r))))
                  (when dir (cache/store! dir cname base (or (:compiler-version r) cv) (:classes r)))
                  (define-all! cname (:classes r) false)))))))))
