(ns ckway.reify
  "`kt/reify` (DESIGN-2 rule 10): implement Kotlin (and Java) interfaces from Clojure.

    (kt/reify jobs/Job
      (.run [this] (co/delay 10) (purge))        ; a Kotlin function: `.` prefix
      (allowParallelRun [this] true))            ; a Kotlin property: plain name

  What it expands to: ONE generated class per shape of form (`ckway.bridge.reify-class`, kind `R`, the same
  storage as the call bridges, so a namespace that is AOT-compiled carries it) and an expression that makes
  an instance: `(new ckway.bridge.R_... (object-array [(fn* ...) ...]) nil)`. Each written member is a Clojure
  function of `this` and the Kotlin parameters; the class calls it with the boxed JVM arguments. The
  conversions are in the function (static forms, no reflection): a value class that the JVM slot holds as
  its underlying value is boxed (`box-impl`), a Kotlin function value becomes a Clojure function, the result
  is converted to the declared Kotlin type (number width, Unit, unbox a value class, adapt a function).
  Why generated bytecode for all members and not `reify`: a Clojure `reify` cannot define a method whose
  JVM name has a `-` (a Kotlin member with a value-class parameter or result: `next-4VatxmU`), and a form
  that mixes such a member with plain ones must be one class. One mechanism for every member is simpler
  than two; the price is that annotations and `with-meta` are written here (both are).

  Names (the same rule for every member, decided by the INTERFACE that declares it):
    a Kotlin interface (it has Kotlin metadata): a function is `.name`, a property is `name` (arity
      [this] is the getter, [this value] the setter of a `var`);
    a Java interface (no Kotlin metadata, `java.lang.Runnable`): the plain Java method name, as in `reify`.
  Interfaces of a Kotlin interface are looked up by the same rule, each by what it is. The members that
  are written under an interface are looked up in that interface and its super-interfaces first, then in
  all of them (a flat list, as in `reify`). `toString`, `hashCode` and `equals` can be written too.

  Parameters: `this`, then the receivers of a member extension, then the Kotlin parameters. The count must
  match. A parameter is a plain symbol; its Kotlin type is its type hint (a hint of the user wins). Two
  overloads with the same name and count are told apart by hints on the parameters (`^Integer` or `^int` for
  a Kotlin Int, `^String`, `^fx.Uid` for a value class).

  A member that is not written: an interface default body (JVM default method, or the older style with the
  body in `I$DefaultImpls`) and a default property getter stay. An ABSTRACT member that is not written is a
  run-time error when it is called (`AbstractMethodError` that names the member), as in Clojure `reify`.
  Annotations: metadata of the member name (`^{fx.Route {:path \"/x\"}} .run`) reaches the JVM method; a
  non-map value is the `value` element, `true` is a marker annotation. Metadata of the `kt/reify` form is
  ignored (the object has no name). `with-meta` works. The object is an instance of the generated class,
  which implements every interface; `this` in a body has that class as its type hint.

  A `suspend` member: its body runs as a coroutine body (`ckway.co/run-body`), on its own virtual thread, with
  the binding frame that was captured when the object was made."
  (:require [clojure.string :as str]
            [ckway.bridge :as bridge]
            [ckway.meta :as meta]
            [ckway.resolve :as r])
  (:import [java.lang.invoke MethodType]
           [java.lang.reflect GenericArrayType Method Modifier ParameterizedType Type TypeVariable WildcardType]))

(set! *warn-on-reflection* true)

(defn- fail [msg] (r/fail msg))

;; ---------------------------------------------------------------- the interfaces

(defn- kind-text [^Class c]
  (cond (.isEnum c) "an enum class" (.isAnnotation c) "an annotation class"
        (Modifier/isAbstract (.getModifiers c)) "an abstract class" :else "a class"))

(defn- resolve-interface
  "The interface class for the symbol `sym`: a kt class var or a class that Clojure resolves."
  ^Class [sym]
  (let [v (when (symbol? sym) (try (ns-resolve *ns* sym) (catch Exception _ nil)))
        c (cond (and (var? v) (:kt/class (meta v))) (r/jvm-class (:kt/class (meta v)))
                (class? v) v)]
    (cond
      (nil? c) (fail (str "kt/reify: cannot resolve `" sym "` to an interface. Write a kt class var (`jobs/Job`) or a "
                          "class name that Clojure resolves (`java.lang.Runnable`, `fx.Job2`)."))
      (not (.isInterface ^Class c)) (fail (str "kt/reify takes interfaces only: `" sym "` is " (kind-text c) " (" (.getName ^Class c)
                                               "). A class cannot be implemented by kt/reify."))
      :else c)))

(defn- parse-sections
  "[{:sym :class :forms [member-form ...]} ...]: an interface symbol, then its members."
  [specs]
  (when (empty? specs) (fail "kt/reify needs at least one interface: (kt/reify jobs/Job (.run [this] ...))"))
  (loop [xs (seq specs) out []]
    (if-let [[x & more] xs]
      (cond
        (symbol? x) (recur more (conj out {:sym x :class (resolve-interface x) :forms []}))
        (seq? x) (if (empty? out)
                   (fail (str "kt/reify: a member must follow an interface, but it comes first: " (r/short-pr x)))
                   (recur more (update out (dec (count out)) update :forms conj x)))
        :else (fail (str "kt/reify: expected an interface or a member (name [this ...] body...), got " (r/short-pr x))))
      out)))

(defn- interface-chain
  "The classes and all their super-interfaces, each once, a class before its super-interfaces."
  [classes]
  (reduce (fn walk [acc ^Class c]
            (if (some #(= c %) acc)
              acc
              (reduce walk (conj acc c) (.getInterfaces c))))
          [] classes))

;; ---------------------------------------------------------------- JVM methods

(defn- desc-of ^String [^Method m]
  (.toMethodDescriptorString (MethodType/methodType (.getReturnType m) ^"[Ljava.lang.Class;" (.getParameterTypes m))))

(defn- instance-methods [^Class c]
  (for [^Method m (.getDeclaredMethods c)
        :let [mods (.getModifiers m)]
        :when (and (Modifier/isPublic mods) (not (Modifier/isStatic mods)) (not (.isSynthetic m)) (not (.isBridge m)))]
    m))

(def ^:private object-methods
  "Methods of Object that an interface can declare abstractly (Comparator.equals) but that are never abstract."
  #{["toString" "()Ljava/lang/String;"] ["hashCode" "()I"] ["equals" "(Ljava/lang/Object;)Z"]})

(declare default-impls)

(defn- erasure
  "The erased class of the reflective type `t`, with the type variables in `env` {TypeVariable Type} replaced first."
  ^Class [^Type t env]
  (cond
    (instance? Class t) t
    (instance? ParameterizedType t) (erasure (.getRawType ^ParameterizedType t) env)
    (instance? TypeVariable t) (if-let [r (get env t)]
                                 (erasure r {})
                                 (let [bs (.getBounds ^TypeVariable t)] (if (seq bs) (erasure (first bs) {}) Object)))
    (instance? GenericArrayType t) (.getClass (java.lang.reflect.Array/newInstance (erasure (.getGenericComponentType ^GenericArrayType t) env) 0))
    (instance? WildcardType t) (let [ub (.getUpperBounds ^WildcardType t)] (if (seq ub) (erasure (first ub) env) Object))
    :else Object))

(defn- super-envs
  "{super-interface {TypeVariable Type}}: for every super-interface of `c` (transitive) the type arguments that
  `c` gives its type parameters (`StrVis : Vis<String>` gives {Vis {T String}})."
  [^Class c]
  (letfn [(go [^Class k env acc]
            (reduce (fn [acc ^Type gi]
                      (if (instance? ParameterizedType gi)
                        (let [^Class raw (.getRawType ^ParameterizedType gi)
                              env2 (zipmap (.getTypeParameters raw)
                                           (map (fn [^Type a] (if (instance? TypeVariable a) (get env a a) a))
                                                (.getActualTypeArguments ^ParameterizedType gi)))]
                          (go raw env2 (assoc acc raw env2)))
                        (go gi {} (assoc acc gi {}))))
                    acc (.getGenericInterfaces k)))]
    (go c {} {})))

(defn- bridged
  "{[name desc] [name desc2]}: an abstract method of a super-interface that a method of a sub-interface overrides
  with more specific types (`Vis<T>.visit(Object)Object` and `StrVis.visit(String)String` for `StrVis : Vis<String>`).
  The JVM class needs a bridge method for the first, as kotlinc and javac make one."
  [chain]
  (into {}
        (for [^Class c2 chain
              [^Class c1 env] (super-envs c2)
              :when (contains? (set chain) c1)
              ^Method m1 (instance-methods c1)
              :when (Modifier/isAbstract (.getModifiers m1))
              ^Method m2 (instance-methods c2)
              :when (and (= (.getName m1) (.getName m2))
                         (not= (desc-of m1) (desc-of m2))
                         (= (mapv #(r/box-class (erasure % env)) (.getGenericParameterTypes m1))
                            (mapv #(r/box-class %) (.getParameterTypes m2))))]
          [[(.getName m1) (desc-of m1)] [(.getName m2) (desc-of m2)]])))

(defn- jvm-methods
  "{[name desc] {:class declaring-interface :method Method :abstract? bool :bridge-to [name desc] :conflict [classes]}}
  of the interface chain. Of the same method in an interface and its sub-interface the sub-interface wins.
  `:bridge-to`: the method is overridden with more specific types (see `bridged`). `:conflict`: unrelated
  interfaces that all have a body for it (default method or `$DefaultImpls`): the JVM cannot choose."
  [chain]
  (let [all (for [^Class c chain, ^Method m (instance-methods c)] [[(.getName m) (desc-of m)] c m])
        br (bridged chain)]
    (into {}
          (for [[k es] (group-by first all)
                :let [best (remove (fn [[_ ^Class c _]] (some (fn [[_ ^Class o _]] (and (not= o c) (.isAssignableFrom c o))) es)) es)
                      [_ c ^Method m] (first best)
                      bodies (filter (fn [[_ ^Class c ^Method x]] (or (not (Modifier/isAbstract (.getModifiers x))) (default-impls c x))) best)]]
            [k (cond-> {:class c :method m
                        :abstract? (and (not (object-methods k)) (every? (fn [[_ _ ^Method x]] (Modifier/isAbstract (.getModifiers x))) best))}
                 (br k) (assoc :bridge-to (br k))
                 (and (not (object-methods k)) (> (count bodies) 1)) (assoc :conflict (mapv second bodies)))]))))

;; ---------------------------------------------------------------- members that can be written

;; A member: {:key "name"/".name" :kind :fn|:get|:set|:java :iface binary :jvm {:name :desc}
;;            :suspend? bool :slots [{:name :type <kotlin type>|nil :jvm-type "int"}] :ret <kotlin type>
;;            :ret-jvm "int" (Java members) :signature text}
;; The slots are what the body takes after `this`: receivers of a member extension, then the parameters.

(defn- slots-of
  "Slots of a Kotlin declaration `d` whose JVM method has descriptor `desc`, or nil when they do not fit."
  [d desc suspend? extra]
  (let [jts (cond-> (vec (:params (meta/desc-types desc))) suspend? pop)
        ks (concat (for [rcv (:receivers d) :when (not= :dispatch (:role rcv))]
                     {:name (or (:name rcv) "receiver") :type (:type rcv)})
                   extra)]
    (when (= (count jts) (count ks))
      (mapv (fn [k jt] (assoc k :jvm-type jt)) ks jts))))

(defn- kotlin-members [^Class c]
  (for [d (meta/class-members (.getName c))
        :when (and (#{:function :property} (:kind d)) (some #(= :dispatch (:role %)) (:receivers d)))
        m (case (:kind d)
            :function
            (let [jvm (:jvm d) suspend? (contains? (:flags d) :suspend)]
              (when (and jvm (not (:field jvm)) (not (:static? jvm)))
                [{:key (:var-name d) :kind :fn :suspend? suspend? :ret (:return d) :signature (:signature d)
                  :jvm {:name (:name jvm) :desc (:desc jvm)}
                  :slots (slots-of d (:desc jvm) suspend? (for [p (:params d)] {:name (:name p) :type (:type p)}))}]))
            :property
            (let [g (:getter d) s (:setter d)]
              (concat
               (when (and g (not (:static? g)))
                 [{:key (:var-name d) :kind :get :ret (:return d) :signature (:signature d)
                   :jvm {:name (:name g) :desc (:desc g)} :slots (slots-of d (:desc g) false [])}])
               (when (and s (not (:static? s)) (contains? (:flags d) :mutable) (contains? #{nil :public} (:setter-visibility d)))
                 [{:key (:var-name d) :kind :set :signature (:signature d)
                   :jvm {:name (:name s) :desc (:desc s)}
                   :slots (slots-of d (:desc s) false [{:name "value" :type (:return d)}])}]))))
        :when (and m (:slots m))]
    (assoc m :iface (.getName c))))

(defn- simple-name [^String n] (subs n (inc (max (.lastIndexOf n ".") (.lastIndexOf n "$")))))

(defn- java-member [^Class owner ^Method m]
  (let [ps (vec (.getParameterTypes m))]
    {:key (.getName m) :kind :java :iface (.getName owner)
     :jvm {:name (.getName m) :desc (desc-of m)}
     :slots (vec (map-indexed (fn [i ^Class p] {:name (str "arg" i) :jvm-type (.getName p)}) ps))
     :ret-jvm (.getName (.getReturnType m))
     :signature (str (simple-name (.getName (.getReturnType m))) " " (.getName m) "("
                     (str/join ", " (map #(simple-name (.getName ^Class %)) ps)) ")")}))

(defn- kotlin-interface? [^Class c]
  (boolean (some #(= :class (:kind %)) (meta/class-members (.getName c)))))

(defn- members-of [chain jvm]
  (let [twin? (fn [m] (:bridge-to (get jvm [(:name (:jvm m)) (:desc (:jvm m))])))
        from-chain (for [^Class c chain
                         m (if (kotlin-interface? c)
                             (filter #(contains? jvm [(:name (:jvm %)) (:desc (:jvm %))]) (kotlin-members c))
                             (map #(java-member c %) (instance-methods c)))
                         :when (not (twin? m))]
                     m)
        from-object (for [^Method m (.getDeclaredMethods Object)
                          :when (object-methods [(.getName m) (desc-of m)])]
                      (java-member Object m))]
    (->> (concat from-chain from-object)
         (reduce (fn [[seen out] m] (let [k [(:key m) (:name (:jvm m)) (:desc (:jvm m))]]
                                      (if (seen k) [seen out] [(conj seen k) (conj out m)])))
                 [#{} []])
         second)))

;; ---------------------------------------------------------------- finding the member for a written form

(defn- written-form
  "How a member is written: `(.run [this])`, `(level [this value])`."
  [m]
  (str "(" (:key m) " [" (str/join " " (cons "this" (map :name (:slots m)))) "])"))

(defn- members-text [members]
  (str/join "\n"
            (for [[iface ms] (group-by :iface (remove #(= "java.lang.Object" (:iface %)) members))]
              (str "  " iface (if (= :java (:kind (first ms))) " (Java: plain method names)" " (Kotlin)") "\n"
                   (str/join "\n" (for [m ms] (str "    " (written-form m) "  " (:signature m))))))))

(defn- candidates-text [ms]
  (str/join "\n" (for [m ms] (str "    " (written-form m) "  " (:signature m)))))

(defn- slot-class ^Class [slot]
  (or (some-> slot :type :value-class :class r/jvm-class) (r/jvm-class (:jvm-type slot))))

(defn- hints-fit? [m hints]
  (every? true? (map (fn [^Class h slot]
                       (or (nil? h)
                           (let [sc (slot-class slot)] (and sc (= (r/box-class h) (r/box-class sc))))))
                     hints (:slots m))))

(declare hint-name)

(defn- pick-member
  "The member that the written form `w` implements, or a kt error."
  [members chain-names {:keys [name argc hints] :as w}]
  (let [key (str name)
        by-key (filter #(= key (:key %)) members)
        in-section (filter #(contains? chain-names (:iface %)) by-key)
        cands (if (seq in-section) in-section by-key)
        by-arity (filter #(= argc (inc (count (:slots %)))) cands)]
    (cond
      (empty? by-key)
      (fail (str "kt/reify: `" key "` is not a member of the interfaces. Members that you can write:\n" (members-text members)
                 "\n  A Kotlin function is written with a `.` prefix (`.run`), a Kotlin property with its plain name, "
                 "a member of a Java interface with its Java method name."))
      (empty? by-arity)
      (fail (str "kt/reify: `" key "` takes a different number of parameters than " argc " (`this` counts). Declared:\n"
                 (candidates-text cands)))
      (= 1 (count by-arity)) (first by-arity)
      :else
      (let [fit (filter #(hints-fit? % hints) by-arity)]
        (if (= 1 (count fit))
          (first fit)
          (let [shown (if (seq fit) fit by-arity)
                diff (first (filter (fn [i] (> (count (distinct (map #(hint-name (nth (:slots %) i)) shown))) 1))
                                    (range (dec argc))))]
            (fail (str "kt/reify: `" key "` with " argc (if (= 1 argc) " parameter" " parameters") " is ambiguous. Candidates:\n"
                       (candidates-text shown)
                       (if diff
                         (str "\n  Tell them apart with a type hint on a parameter, as in `reify`: parameter " (inc diff)
                              " (after `this`) is "
                              (str/join " or " (map #(str "^" (or (hint-name (nth (:slots %) diff)) "java.lang.Object")) shown)))
                         "\n  They differ by more than the types of their parameters, so no type hint can select one")
                       (when (and diff (empty? fit)) ". The hints that you wrote fit none of them")
                       "."))))))))

;; ---------------------------------------------------------------- the conversions of one member

(defn- hint-name
  "Class name for the type hint of the parameter in `slot` (the JVM class, boxed; the value class itself), or nil."
  [slot]
  (let [^Class c (slot-class slot)]
    (when (and c (not= Object c) (not (.isArray c)) (not= Void/TYPE c))
      (.getName (r/box-class c)))))

(defn- slot-in
  "[hint-class-name conv] for an argument that Kotlin passes in `slot`: `conv` makes the form of the value
  that the body sees from the form of the raw JVM argument."
  [slot]
  (let [t (:type slot)
        vc (when t (r/vc-conv t (:jvm-type slot)))
        td (when t (r/type-descriptor t))]
    (cond
      vc [(-> vc :vc :class) (fn [raw] (r/box-form vc raw))]
      (and td (#{:fn :unit} (:k td))) [nil (fn [raw] `(ckway.rt/<-kotlin ~td ~raw))]
      :else [(hint-name slot) identity])))

(def ^:private number-kinds #{:int :long :short :byte :double :float :char :bool})

(defn- ret-jvm-name [m]
  (case (:kind m)
    :set "void"
    :java (:ret-jvm m)
    (:return (meta/desc-types (:desc (:jvm m))))))

(defn- result-form
  "The form that converts the value of `body` to what the JVM method of `m` returns (as function adapters do)."
  [m body]
  (let [jt (ret-jvm-name m)]
    (case (:kind m)
      :set `(do ~body nil)
      :java (cond (= "void" jt) `(do ~body nil)
                  (r/jvm-descriptor jt) `(ckway.rt/->kotlin ~(r/jvm-descriptor jt) ~body)
                  :else body)
      (let [t (:ret m)
            td (r/type-descriptor t)
            vc (when-not (:suspend? m) (r/vc-conv t jt))]
        (cond
          vc (r/unbox-form (assoc vc :name "result" :result? true) body)
          (#{:fn :fi} (:k td))
          (let [iface (if (:fn-type t)
                        (str "kotlin.jvm.functions.Function" (cond-> (:arity td) (:suspend? td) inc))
                        (:class td))]
            (first (r/adapter-form (r/adapter-spec t iface (:signature m)) iface body)))
          (= :unit (:k td)) `(do ~body kotlin.Unit/INSTANCE)
          (number-kinds (:k td)) `(ckway.rt/->kotlin ~td ~body)
          (r/check-result? td (:suspend? m)) `(ckway.rt/->kotlin ~td ~body)
          :else body)))))

(defn- bind-symbol
  "The user's parameter symbol with the Kotlin type as a hint when the user wrote none. A primitive hint
  of the user is the boxed class (the body gets objects)."
  [p hint]
  (let [tag (:tag (meta p))]
    (cond
      (and tag (symbol? tag) (#{'int 'long 'short 'byte 'double 'float 'char 'boolean} tag))
      (vary-meta p assoc :tag (symbol (.getName (r/box-class ^Class (r/tag->class *ns* tag)))))
      tag p
      hint (vary-meta p assoc :tag (symbol hint))
      :else p)))

(defn- member-fn
  "The Clojure function for the written form `w` of member `m`. It takes `this`, the raw JVM arguments
  (boxed) and for a suspend member the continuation last."
  [{:keys [params body member name] :as w} cname frame]
  (let [m member
        raw (vec (repeatedly (count params) #(gensym "raw")))
        k (gensym "k")
        ins (map slot-in (:slots m))
        bindings (vec (concat [(bind-symbol (first params) cname) (first raw)]
                              (mapcat (fn [p [hint conv] r] [(bind-symbol p hint) (conv r)]) (rest params) ins (rest raw))))
        result (result-form m (if (= 1 (count body)) (first body) `(do ~@body)))
        fname (symbol (str/replace (str (simple-name (:iface m)) "_" name) #"[^A-Za-z0-9_]" "_"))]
    (if (:suspend? m)
      `(fn* ~fname [~@raw ~k] (ckway.co/run-body ~k ~frame (fn* [] (let ~bindings ~result))))
      `(fn* ~fname [~@raw] (let ~bindings ~result)))))

;; ---------------------------------------------------------------- annotations

(defn- element-value [^Class ac ^String n x]
  (let [^Method am (try (.getMethod ac n (make-array Class 0))
                        (catch NoSuchMethodException _
                          (fail (str "kt/reify: the annotation " (.getName ac) " has no element `" n "`."))))
        scalar (fn scalar [^Class t v]
                 (let [bad #(fail (str "kt/reify: element `" n "` of " (.getName ac) " takes " (.getSimpleName t) ", got " (r/short-pr v)))]
                   (cond
                     (= String t) (if (string? v) v (bad))
                     (= Boolean/TYPE t) (if (boolean? v) v (bad))
                     (= Character/TYPE t) (if (char? v) v (bad))
                     (.isPrimitive t) (if (number? v)
                                        (condp = t
                                          Integer/TYPE (int v) Long/TYPE (long v) Short/TYPE (short v) Byte/TYPE (byte v)
                                          Float/TYPE (float v) Double/TYPE (double v))
                                        (bad))
                     :else (fail (str "kt/reify: element `" n "` of " (.getName ac) " has the type " (.getSimpleName t)
                                      ", which kt/reify does not support (strings, numbers, booleans, chars and arrays of them)")))))
        rt (.getReturnType am)]
    (if (.isArray rt)
      (vec (map #(scalar (.getComponentType rt) %) (if (sequential? x) x [x])))
      (scalar rt x))))

(defn annotations-of
  "[{:class :elements}] from the metadata of the member name symbol."
  [name-sym]
  (vec (for [[k v] (sort-by (comp str key) (r/annotation-meta name-sym))
             :let [^Class ac (r/tag->class *ns* k)
                   elems (cond (or (true? v) (nil? v) (and (map? v) (empty? v))) {}
                               (map? v) (into {} (for [[n x] v] [(clojure.core/name n) x]))
                               :else {"value" v})]]
         {:class (.getName ac)
          :elements (into (sorted-map) (for [[n x] elems] [n (element-value ac n x)]))})))

;; ---------------------------------------------------------------- one written form

(defn- parse-member [form]
  (let [[nm params & body] form]
    (when-not (and (symbol? nm) (vector? params))
      (fail (str "kt/reify: a member is (name [this ...] body...), got " (r/short-pr form))))
    (when (empty? params) (fail (str "kt/reify: `" nm "` needs `this` as its first parameter: (" nm " [this ...] ...)")))
    (when-not (every? symbol? params)
      (fail (str "kt/reify: the parameters of `" nm "` must be plain symbols (no destructuring, no `&`), got " (r/short-pr params))))
    (when (some #{'&} params)
      (fail (str "kt/reify: `&` is not allowed in the parameters of `" nm "`: they must be plain symbols")))
    {:name nm :params params :body body :argc (count params)
     :hints (mapv #(some->> (:tag (meta %)) (r/tag->class *ns*)) (rest params))
     :annotations (annotations-of nm)}))

(defn- default-impls
  "The static method in `I$DefaultImpls` that holds the body of the abstract JVM method `m` of `c`, or nil."
  ^Method [^Class c ^Method m]
  (when-let [^Class impls (r/jvm-class (str (.getName c) "$DefaultImpls"))]
    (let [want (vec (cons c (.getParameterTypes m)))]
      (first (for [^Method s (.getDeclaredMethods impls)
                   :when (and (= (.getName m) (.getName s)) (Modifier/isStatic (.getModifiers s))
                              (= want (vec (.getParameterTypes s))) (= (.getReturnType m) (.getReturnType s)))]
               s)))))

(defn- class-methods
  "The methods of the generated class, written ones first in the written order."
  [written jvm members]
  (let [by-key (into {} (map (fn [w] [[(:name (:jvm (:member w))) (:desc (:jvm (:member w)))] w]) written))
        sig-of (fn [[n d] ^Class c] (or (some #(when (= [n d] [(:name (:jvm %)) (:desc (:jvm %))]) (:signature %)) members)
                                        (str (.getName c) "." n d)))]
    (doseq [[[n d :as k] {:keys [conflict class]}] jvm
            :when (and conflict (not (by-key k)))]
      (let [m (first (filter #(= [n d] [(:name (:jvm %)) (:desc (:jvm %))]) members))]
        (fail (str "kt/reify: the member `" (if m (:key m) n) "` has a default body in two unrelated interfaces ("
                   (str/join " and " (map #(.getName ^Class %) conflict))
                   "), so the JVM cannot choose one (IncompatibleClassChangeError: Conflicting default methods). Write it yourself"
                   (when m (str ": " (written-form m) "  " (:signature m))) "."))))
    (concat
     (for [w written
           :let [j (:jvm (:member w))]]
       {:impl :fn :name (:name j) :desc (:desc j) :idx (:idx w) :annotations (:annotations w)})
     (for [[[n d :as k] {:keys [abstract? class method bridge-to]}] (sort-by key jvm)
           :when (and abstract? (not (by-key k)))]
       (cond
         bridge-to {:impl :bridge :name n :desc d :target-desc (second bridge-to)}
         :else
         (if-let [s (default-impls class method)]
           {:impl :delegate :name n :desc d :impls (.getName (.getDeclaringClass s)) :impls-desc (desc-of s)}
           {:impl :abstract :name n :desc d
            :message (str "kt/reify: the abstract member `" (sig-of k class) "` was called, but the kt/reify form does not write it")}))))))

(defn expand
  "Expansion of `(kt/reify spec...)` (see the namespace docstring)."
  [specs]
  (let [sections (parse-sections specs)
        classes (vec (distinct (map :class sections)))
        chain (interface-chain classes)
        jvm (jvm-methods chain)
        members (members-of chain jvm)
        written (vec (map-indexed
                      (fn [i [sec form]]
                        (let [w (parse-member form)
                              names (set (map #(.getName ^Class %) (interface-chain [(:class sec)])))
                              m (pick-member members names w)]
                          (when (> (+ (:argc w) (if (:suspend? m) 1 0)) 20)
                            (fail (str "kt/reify: `" (:name w) "` has more than 20 parameters (with `this`): not supported")))
                          (assoc w :member m :idx i)))
                      (for [sec sections, form (:forms sec)] [sec form])))
        _ (doseq [[k ws] (group-by #(let [j (:jvm (:member %))] [(:name j) (:desc j)]) written)
                  :when (> (count ws) 1)]
            (fail (str "kt/reify: the member `" (:key (:member (first ws))) "` is written twice (" (str/join ", " (map #(r/short-pr (list (:name %) (vec (:params %)))) ws)) ")")))
        spec {:ifaces (mapv #(.getName ^Class %) classes) :iface-classes classes :methods (vec (class-methods written jvm members))}
        cname (bridge/reify-class (simple-name (.getName ^Class (first classes))) spec)
        frame (gensym "frame")
        fns (mapv #(member-fn % cname frame) written)]
    `(new ~(symbol cname)
          ~(if (some #(:suspend? (:member %)) written)
             `(let [~frame (ckway.co/capture-frame)] (object-array [~@fns]))
             `(object-array [~@fns]))
          nil)))

(defn form-info
  "Compile-time class of a `(kt/reify ...)` form (`ckway.resolve/form-info`): the generated class, which is
  a subtype of every interface of the form. nil when the form has an error (the expansion reports it)."
  [form]
  (try
    (let [x (macroexpand-1 form)]
      (when (and (seq? x) (= 'new (first x)))
        (r/jvm-class (str (second x)))))
    (catch clojure.lang.ExceptionInfo e
      (if (:kt/error (ex-data e)) nil (throw e)))))
