(ns ckway.reify
  "`kt/reify` (README rule 10): implement Kotlin (and Java) interfaces from Clojure.

    (kt/reify jobs/Job
      (.run [this] (co/delay 10) (purge))        ; a Kotlin function: `.` prefix
      (allowParallelRun [this] true))            ; a Kotlin property: plain name

  What it expands to: ONE generated class per shape of form (`ckway.bridge.reify-class`, kind `R`, the same
  storage as the call bridges, so a namespace that is AOT-compiled carries it) and an expression that makes
  an instance: `(new ckway.bridge.R_... (object-array [(fn* ...) ...]) nil)`. Each written member is a Clojure
  function of `this` and the Kotlin parameters; the class calls it with the boxed JVM arguments. The
  conversions are in the function (static forms, no reflection): a value class that the JVM slot holds as
  its underlying value is boxed (`box-impl`), a Kotlin function value becomes a Clojure function, the result
  is converted to the declared Kotlin type (number width, Unit, unbox a value class, adapt a function).
  Why generated bytecode for all members and not `reify`: a Clojure `reify` cannot define a method whose
  JVM name has a `-` (a Kotlin member with a value-class parameter or result: `next-4VatxmU`), and a form
  that mixes such a member with plain ones must be one class. One mechanism for every member is simpler
  than two; the price is that annotations and `with-meta` are written here (both are).

  Names (the same rule for every member, decided by the INTERFACE that declares it):
    a Kotlin interface (it has Kotlin metadata): a function is `.name`, a property is `name` (arity
      [this] is the getter, [this value] the setter of a `var`);
    a Java interface (no Kotlin metadata, `java.lang.Runnable`): the plain Java method name, as in `reify`.
  Interfaces of a Kotlin interface are looked up by the same rule, each by what it is. The members that
  are written under an interface are looked up in that interface and its super-interfaces first, then in
  all of them (a flat list, as in `reify`). `toString`, `hashCode` and `equals` can be written too.

  Parameters: `this`, then the receivers of a member extension, then the Kotlin parameters. The count must
  match. A parameter is a plain symbol; its Kotlin type is its type hint (a hint of the user wins). Two
  overloads with the same name and count are told apart by hints on the parameters (`^Integer` or `^int` for
  a Kotlin Int, `^String`, `^fx.Uid` for a value class).

  Narrowed types: an interface that overrides a member with a more specific result or parameter type
  (`StrSrc : Src { override fun get(): String }`, `StrVis : Vis<String>`) has ONE writable member, the most specific
  one. The class implements that JVM method and a bridge method for every JVM signature it overrides (the erased
  one, the covariant ones), as kotlinc does; a bridge to a method that takes or returns a value class unboxes and
  boxes it.

  A member that is not written: an interface default body (JVM default method, or the older style with the
  body in `I$DefaultImpls`) and a default property getter stay. An ABSTRACT member that is not written is a
  run-time error when it is called (`AbstractMethodError` that names the member), as in Clojure `reify`.
  Annotations: metadata of the member name (`^{fx.Route {:path \"/x\"}} .run`) reaches the JVM method; a
  non-map value is the `value` element, `true` is a marker annotation. Metadata of the `kt/reify` form is
  ignored (the object has no name). `with-meta` works. The object is an instance of the generated class,
  which implements every interface; `this` in a body has that class as its type hint.

  A `suspend` member: its body runs as a coroutine body (`ckway.co/run-body`), on its own virtual thread, with
  the binding frame that was captured when the object was made."
  (:require [clojure.string :as str]
            [ckway.bridge :as bridge]
            [ckway.meta :as meta]
            [ckway.resolve :as r])
  (:import [java.lang.invoke MethodType]
           [java.lang.reflect GenericArrayType Method Modifier ParameterizedType Type TypeVariable WildcardType]
           [kotlin.metadata.jvm KotlinClassMetadata$Class]))

(set! *warn-on-reflection* true)

(defn- fail [msg] (r/fail msg))

;; ---------------------------------------------------------------- the interfaces

(defn- kind-text [^Class c]
  (cond (.isEnum c) "an enum class" (.isAnnotation c) "an annotation class"
        (Modifier/isAbstract (.getModifiers c)) "an abstract class" :else "a class"))

(defn- resolve-interface
  "The interface class for the symbol `sym`: a kt class var or a class that Clojure resolves."
  ^Class [sym]
  (let [v (when (symbol? sym) (try (ns-resolve *ns* sym) (catch Exception _ nil)))
        c (cond (and (var? v) (:kt/class (meta v))) (r/jvm-class (:kt/class (meta v)))
                (class? v) v)]
    (cond
      (nil? c) (fail (str "kt/reify: cannot resolve `" sym "` to an interface. Write a kt class var (`jobs/Job`) or a "
                          "class name that Clojure resolves (`java.lang.Runnable`, `fx.Job2`)."))
      (not (.isInterface ^Class c)) (fail (str "kt/reify takes interfaces only: `" sym "` is " (kind-text c) " (" (.getName ^Class c)
                                               "). A class cannot be implemented by kt/reify."))
      :else c)))

(defn- parse-sections
  "[{:sym :class :forms [member-form ...]} ...]: an interface symbol, then its members."
  [specs]
  (when (empty? specs) (fail "kt/reify needs at least one interface: (kt/reify jobs/Job (.run [this] ...))"))
  (loop [xs (seq specs) out []]
    (if-let [[x & more] xs]
      (cond
        (symbol? x) (recur more (conj out {:sym x :class (resolve-interface x) :forms []}))
        (seq? x) (if (empty? out)
                   (fail (str "kt/reify: a member must follow an interface, but it comes first: " (r/short-pr x)))
                   (recur more (update out (dec (count out)) update :forms conj x)))
        :else (fail (str "kt/reify: expected an interface or a member (name [this ...] body...), got " (r/short-pr x))))
      out)))

(defn- interface-chain
  "The classes and all their super-interfaces, each once, a class before its super-interfaces."
  [classes]
  (reduce (fn walk [acc ^Class c]
            (if (some #(= c %) acc)
              acc
              (reduce walk (conj acc c) (.getInterfaces c))))
          [] classes))

;; ---------------------------------------------------------------- JVM methods

(defn- desc-of ^String [^Method m]
  (.toMethodDescriptorString (MethodType/methodType (.getReturnType m) ^"[Ljava.lang.Class;" (.getParameterTypes m))))

(defn- instance-methods [^Class c]
  (for [^Method m (.getDeclaredMethods c)
        :let [mods (.getModifiers m)]
        :when (and (Modifier/isPublic mods) (not (Modifier/isStatic mods)) (not (.isSynthetic m)) (not (.isBridge m)))]
    m))

(def ^:private object-methods
  "Methods of Object that an interface can declare abstractly (Comparator.equals) but that are never abstract."
  #{["toString" "()Ljava/lang/String;"] ["hashCode" "()I"] ["equals" "(Ljava/lang/Object;)Z"]})

(declare default-impls)

(defn- erasure
  "The erased class of the reflective type `t`, with the type variables in `env` {TypeVariable Type} replaced first."
  ^Class [^Type t env]
  (cond
    (instance? Class t) t
    (instance? ParameterizedType t) (erasure (.getRawType ^ParameterizedType t) env)
    (instance? TypeVariable t) (if-let [r (get env t)]
                                 (erasure r {})
                                 (let [bs (.getBounds ^TypeVariable t)] (if (seq bs) (erasure (first bs) {}) Object)))
    (instance? GenericArrayType t) (.getClass (java.lang.reflect.Array/newInstance (erasure (.getGenericComponentType ^GenericArrayType t) env) 0))
    (instance? WildcardType t) (let [ub (.getUpperBounds ^WildcardType t)] (if (seq ub) (erasure (first ub) env) Object))
    :else Object))

(defn- super-envs
  "{super-interface {TypeVariable Type}}: for every super-interface of `c` (transitive) the type arguments that
  `c` gives its type parameters (`StrVis : Vis<String>` gives {Vis {T String}})."
  [^Class c]
  (letfn [(go [^Class k env acc]
            (reduce (fn [acc ^Type gi]
                      (if (instance? ParameterizedType gi)
                        (let [^Class raw (.getRawType ^ParameterizedType gi)
                              env2 (zipmap (.getTypeParameters raw)
                                           (map (fn [^Type a] (if (instance? TypeVariable a) (get env a a) a))
                                                (.getActualTypeArguments ^ParameterizedType gi)))]
                          (go raw env2 (assoc acc raw env2)))
                        (go gi {} (assoc acc gi {}))))
                    acc (.getGenericInterfaces k)))]
    (go c {} {})))

(declare bridged)

(defn- jvm-methods
  "{[name desc] {:class declaring-interface :method Method :abstract? bool :bridge-to [name desc] :conflict [classes]}}
  of the interface chain. Of the same method in an interface and its sub-interface the sub-interface wins.
  `:bridge-to`: the method is overridden with more specific types (see `bridged`). `:conflict`: unrelated
  interfaces that all have a body for it (default method or `$DefaultImpls`): the JVM cannot choose."
  [chain]
  (let [all (for [^Class c chain, ^Method m (instance-methods c)] [[(.getName m) (desc-of m)] c m])
        br (bridged chain)]
    (into {}
          (for [[k es] (group-by first all)
                :let [best (remove (fn [[_ ^Class c _]] (some (fn [[_ ^Class o _]] (and (not= o c) (.isAssignableFrom c o))) es)) es)
                      [_ c ^Method m] (first best)
                      bodies (filter (fn [[_ ^Class c ^Method x]] (or (not (Modifier/isAbstract (.getModifiers x))) (default-impls c x))) best)]]
            [k (cond-> {:class c :method m
                        :abstract? (and (not (object-methods k)) (every? (fn [[_ _ ^Method x]] (Modifier/isAbstract (.getModifiers x))) best))}
                 (br k) (assoc :bridge-to (br k))
                 (and (not (object-methods k)) (> (count bodies) 1)) (assoc :conflict (mapv second bodies)))]))))

;; ---------------------------------------------------------------- members that can be written

;; A member: {:key "name"/".name" :kind :fn|:get|:set|:java :iface binary :jvm {:name :desc}
;;            :suspend? bool :slots [{:name :type <kotlin type>|nil :jvm-type "int"}] :ret <kotlin type>
;;            :ret-jvm "int" (Java members) :signature text}
;; The slots are what the body takes after `this`: receivers of a member extension, then the parameters.

(defn- slots-of
  "Slots of a Kotlin declaration `d` whose JVM method has descriptor `desc`, or nil when they do not fit."
  [d desc suspend? extra]
  (let [jts (cond-> (vec (:params (meta/desc-types desc))) suspend? pop)
        ks (concat (for [rcv (:receivers d) :when (not= :dispatch (:role rcv))]
                     {:name (or (:name rcv) "receiver") :type (:type rcv)})
                   extra)]
    (when (= (count jts) (count ks))
      (mapv (fn [k jt] (assoc k :jvm-type jt)) ks jts))))

(defn- own-and-function-type [^Class c]
  ;; `Filter : (Handler) -> Handler` has the `invoke` of its function type: with the types of the supertype, which the
  ;; generic `invoke` of `Function1` that the chain also holds does not know. A value class is the box in a generic position.
  (concat (meta/own-declarations c)
          (for [d (meta/function-type-decls c)]
            (update d :params (fn [ps] (mapv #(if (:value-class? (:type %))
                                                (assoc % :type {:class "kotlin/Any" :nullable? true :args [] :value-class? false
                                                                :fun-interface? false :fn-type nil :alias nil :type-param nil})
                                                %)
                                             ps))))))

(defn- kotlin-members [^Class c]
  (for [d (own-and-function-type c)
        :when (and (#{:function :property} (:kind d)) (some #(= :dispatch (:role %)) (:receivers d)))
        m (case (:kind d)
            :function
            (let [jvm (:jvm d) suspend? (contains? (:flags d) :suspend)]
              (when (and jvm (not (:field jvm)) (not (:static? jvm)))
                [{:key (:var-name d) :kind :fn :suspend? suspend? :ret (:return d) :signature (:signature d)
                  :jvm {:name (:name jvm) :desc (:desc jvm)}
                  :slots (slots-of d (:desc jvm) suspend? (for [p (:params d)] {:name (:name p) :type (:type p)}))}]))
            :property
            (let [g (:getter d) s (:setter d)]
              (concat
               (when (and g (not (:static? g)))
                 [{:key (:var-name d) :kind :get :ret (:return d) :signature (:signature d)
                   :jvm {:name (:name g) :desc (:desc g)} :slots (slots-of d (:desc g) false [])}])
               (when (and s (not (:static? s)) (contains? (:flags d) :mutable) (contains? #{nil :public} (:setter-visibility d)))
                 [{:key (:var-name d) :kind :set :signature (:signature d)
                   :jvm {:name (:name s) :desc (:desc s)}
                   :slots (slots-of d (:desc s) false [{:name "value" :type (:return d)}])}]))))
        :when (and m (:slots m))]
    (assoc m :iface (.getName c))))

(defn- simple-name [^String n] (subs n (inc (max (.lastIndexOf n ".") (.lastIndexOf n "$")))))

(defn- java-member [^Class owner ^Method m]
  (let [ps (vec (.getParameterTypes m))]
    {:key (.getName m) :kind :java :iface (.getName owner)
     :jvm {:name (.getName m) :desc (desc-of m)}
     :slots (vec (map-indexed (fn [i ^Class p] {:name (str "arg" i) :jvm-type (.getName p)}) ps))
     :ret-jvm (.getName (.getReturnType m))
     :signature (str (simple-name (.getName (.getReturnType m))) " " (.getName m) "("
                     (str/join ", " (map #(simple-name (.getName ^Class %)) ps)) ")")}))

(defn- kotlin-interface? [^Class c]
  (boolean (some #(= :class (:kind %)) (meta/class-members (.getName c)))))

(defn- jvm-key [m] [(:name (:jvm m)) (:desc (:jvm m))])

(defn- members-of [chain jvm]
  (let [all (concat (for [^Class c chain
                          m (if (kotlin-interface? c)
                              (filter #(contains? jvm (jvm-key %)) (kotlin-members c))
                              (map #(java-member c %) (instance-methods c)))]
                      m)
                    (for [^Method m (.getDeclaredMethods Object)
                          :when (object-methods [(.getName m) (desc-of m)])]
                      (java-member Object m)))
        present (set (map jvm-key all))
        ;; the member of an erased JVM signature is hidden when the more specific member that overrides it is offered
        twin? (fn [m] (when-let [leaf (:bridge-to (get jvm (jvm-key m)))] (contains? present leaf)))]
    (->> all
         (remove twin?)
         (reduce (fn [[seen out] m] (let [k [(:key m) (:name (:jvm m)) (:desc (:jvm m))]]
                                      (if (seen k) [seen out] [(conj seen k) (conj out m)])))
                 [#{} []])
         second)))

;; ---------------------------------------------------------------- finding the member for a written form

(defn- written-form
  "How a member is written: `(.run [this])`, `(level [this value])`."
  [m]
  (str "(" (:key m) " [" (str/join " " (cons "this" (map :name (:slots m)))) "])"))

(defn- members-text [members chain]
  (let [shown (remove #(= "java.lang.Object" (:iface %)) members)]
    (if (seq shown)
      (str/join "\n"
                (for [[iface ms] (group-by :iface shown)]
                  (str "  " iface (if (= :java (:kind (first ms))) " (Java: plain method names)" " (Kotlin)") "\n"
                       (str/join "\n" (for [m ms] (str "    " (written-form m) "  " (:signature m)))))))
      ;; never an empty list for an interface that has methods: show the JVM methods
      (str/join "\n"
                (for [^Class c chain
                      :let [ms (instance-methods c)]
                      :when (seq ms)]
                  (str "  " (.getName c) " (JVM methods)\n"
                       (str/join "\n" (for [^Method m ms] (str "    " (.getName m) (desc-of m))))))))))

(defn- candidates-text [ms]
  (str/join "\n" (for [m ms] (str "    " (written-form m) "  " (:signature m)))))

(defn- slot-class ^Class [slot]
  (or (some-> slot :type :value-class :class r/jvm-class) (r/jvm-class (:jvm-type slot))))

(defn- slot-fits?
  "Do the slots `sa` (of the member of the super-interface; `g` is the generic type of its JVM parameter, `env` the
  type arguments that the sub-interface gives) and `sb` (of the overriding member) stand for the same parameter?
  Only where the super-interface has a type variable is a primitive the same as its box (`Vis<Int>.visit(Object)`
  and `visit(int)`); everywhere else the types must be equal, so `f(Int?)` and `f(Int)` are two members."
  [sa sb ^Type g env]
  (if (instance? TypeVariable g)
    (= (r/box-class (erasure g env)) (r/box-class (slot-class sb)))
    (and (= (slot-class sa) (slot-class sb))
         (or (not (or (-> sa :type :value-class) (-> sb :type :value-class)))
             (= (boolean (-> sa :type :nullable?)) (boolean (-> sb :type :nullable?)))))))

(defn- method-of
  "The public instance method of `c` with JVM name and descriptor `k`, or nil."
  ^Method [^Class c [n d]]
  (first (filter #(and (= n (.getName ^Method %)) (= d (desc-of %))) (instance-methods c))))

(defn- reflection-pairs
  "[[super-key sub-key] ...] by the JVM signatures alone: an abstract method of a super-interface and a method of
  a sub-interface with the same name and the same parameters (those of the super-interface with the type
  arguments of the sub-interface put in), that differ in their descriptors (a covariant result, a more specific
  parameter)."
  [chain]
  (for [^Class c2 chain
        [^Class c1 env] (super-envs c2)
        :when (contains? (set chain) c1)
        ^Method m1 (instance-methods c1)
        :when (Modifier/isAbstract (.getModifiers m1))
        ^Method m2 (instance-methods c2)
        :when (and (= (.getName m1) (.getName m2))
                   (not= (desc-of m1) (desc-of m2))
                   (= (count (.getParameterTypes m1)) (count (.getParameterTypes m2)))
                   (every? true? (map (fn [^Type g ^Class p2]
                                        (if (instance? TypeVariable g)
                                          (= (r/box-class (erasure g env)) (r/box-class p2))
                                          (= (erasure g env) p2)))
                                      (.getGenericParameterTypes m1) (.getParameterTypes m2))))]
    [[(.getName m1) (desc-of m1)] [(.getName m2) (desc-of m2)]]))

(defn- kotlin-pairs
  "[[super-key sub-key] ...] by the Kotlin declarations: the same member (same kind and name, parameters that
  stand for the same types) declared by a super-interface and by a sub-interface under different JVM names or
  descriptors. This finds what the JVM signatures hide: a value class makes the JVM name of the override
  mangled (`id()Object` and `id-z32cIck()I`)."
  [chain]
  (let [in-chain (set chain)
        members (into {} (for [^Class c chain :when (kotlin-interface? c)] [c (vec (kotlin-members c))]))]
    (for [^Class c2 chain
          [^Class c1 env] (super-envs c2)
          :when (and (in-chain c1) (members c1) (members c2))
          a (members c1)
          :let [^Method ma (method-of c1 (jvm-key a))]
          :when (and ma (Modifier/isAbstract (.getModifiers ma)))
          b (members c2)
          :when (and (= (:kind a) (:kind b)) (= (:key a) (:key b))
                     (not= (jvm-key a) (jvm-key b))
                     (= (count (:slots a)) (count (:slots b)))
                     (every? true? (map #(slot-fits? %1 %2 %3 env) (:slots a) (:slots b) (.getGenericParameterTypes ma))))]
      [(jvm-key a) (jvm-key b)])))

(defn- bridge-leaves
  "{[name desc] [leaf-key ...]}: an abstract method of a super-interface and ALL the most specific methods that override
  it with other types, through any number of levels (`Src.get()Object` and the two leaves `S1.get()CharSequence`
  and `S2.get()Comparable` of `S1 : Src`, `S2 : Src`)."
  [chain]
  (let [pairs (distinct (remove (fn [[a b]] (= a b)) (concat (reflection-pairs chain) (kotlin-pairs chain))))
        next-of (reduce (fn [m [a b]] (update m a (fnil conj []) b)) {} pairs)
        leaves (fn leaves [k seen]
                 (if-let [ns (seq (remove seen (get next-of k)))]
                   (mapcat #(leaves % (conj seen k)) ns)
                   (when (seq seen) [k])))]
    (into {} (for [k (keys next-of)
                   :let [ls (vec (distinct (leaves k #{})))]
                   :when (seq ls)]
               [k ls]))))

(defn- bridged
  "{[name desc] [name desc]}: an abstract method of a super-interface and the most specific method that overrides
  it with other types (`Vis<T>.visit(Object)Object` and `StrVis.visit(String)String` for `StrVis : Vis<String>`;
  `Src.get()Object` and `StrSrc.get()String`). Through any number of levels the target is the last override
  (`L1.g()Object`, `L2.g()CharSequence`, `L3.g()String`: both of the first two map to the third). With several
  leaves (`S1.get()CharSequence`, `S2.get()Comparable`) it is the first one. The JVM class needs a bridge method for
  each key, as kotlinc and javac make."
  [chain]
  (into {} (for [[k ls] (bridge-leaves chain)] [k (first ls)])))

(defn- hints-fit?
  "Do the type hints of a written form fit the slots of member `m`? A hint that is exactly the class of the slot
  (`^int` for `Int`, `^Integer` for `Int?`) is the exact fit. A boxed or primitive hint for the other one is a
  loose fit (`^Integer` for `Int` is how `reify` is written). The members that fit exactly are preferred."
  [m hints]
  (let [fits (fn [same?]
               (every? true? (map (fn [^Class h slot]
                                    (or (nil? h) (let [sc (slot-class slot)] (and sc (same? h sc)))))
                                  hints (:slots m))))]
    {:exact (fits =) :loose (fits #(= (r/box-class %1) (r/box-class %2)))}))

(declare hint-name hint-text)

(defn- pick-member
  "The member that the written form `w` implements, or a kt error."
  [members chain chain-names {:keys [name argc hints] :as w}]
  (let [key (str name)
        by-key (filter #(= key (:key %)) members)
        in-section (filter #(contains? chain-names (:iface %)) by-key)
        cands (if (seq in-section) in-section by-key)
        by-arity (filter #(= argc (inc (count (:slots %)))) cands)]
    (cond
      (empty? by-key)
      (fail (str "kt/reify: `" key "` is not a member of the interfaces. Members that you can write:\n" (members-text members chain)
                 "\n  A Kotlin function is written with a `.` prefix (`.run`), a Kotlin property with its plain name, "
                 "a member of a Java interface with its Java method name."))
      (empty? by-arity)
      (fail (str "kt/reify: `" key "` takes a different number of parameters than " argc " (`this` counts). Declared:\n"
                 (candidates-text cands)))
      (= 1 (count by-arity)) (first by-arity)
      :else
      (let [fits (map (fn [m] [m (hints-fit? m hints)]) by-arity)
            exact (map first (filter (comp :exact second) fits))
            fit (if (= 1 (count exact)) exact (map first (filter (comp :loose second) fits)))]
        (if (= 1 (count fit))
          (first fit)
          (let [shown (if (seq fit) fit by-arity)
                diff (first (filter (fn [i] (> (count (distinct (map #(hint-text (nth (:slots %) i)) shown))) 1))
                                    (range (dec argc))))]
            (fail (str "kt/reify: `" key "` with " argc (if (= 1 argc) " parameter" " parameters") " is ambiguous. Candidates:\n"
                       (candidates-text shown)
                       (if diff
                         (str "\n  Tell them apart with a type hint on a parameter, as in `reify`: parameter " (inc diff)
                              " (after `this`) is "
                              (str/join " or " (map #(str "^" (or (hint-text (nth (:slots %) diff)) "java.lang.Object")) shown)))
                         "\n  They differ by more than the types of their parameters, so no type hint can select one")
                       (when (and diff (empty? fit)) ". The hints that you wrote fit none of them")
                       "."))))))))

;; ---------------------------------------------------------------- the conversions of one member

(defn- hint-name
  "Class name for the type hint of the parameter in `slot` (the JVM class, boxed; the value class itself), or nil."
  [slot]
  (let [^Class c (slot-class slot)]
    (when (and c (not= Object c) (not (.isArray c)) (not= Void/TYPE c))
      (.getName (r/box-class c)))))

(defn- hint-text
  "Class name for a hint that tells overloads apart in an error message: the exact class of the slot (`int`, not `java.lang.Integer`)."
  [slot]
  (let [^Class c (slot-class slot)]
    (when (and c (not= Object c) (not (.isArray c)) (not= Void/TYPE c))
      (.getName c))))

(defn- slot-in
  "[hint-class-name conv] for an argument that Kotlin passes in `slot`: `conv` makes the form of the value
  that the body sees from the form of the raw JVM argument."
  [slot]
  (let [t (:type slot)
        vc (when t (r/vc-conv t (:jvm-type slot)))
        td (when t (r/type-descriptor t))]
    (cond
      vc [(-> vc :vc :class) (fn [raw] (r/box-form vc raw))]
      (and td (#{:fn :unit} (:k td))) [nil (fn [raw] `(ckway.rt/<-kotlin ~td ~raw))]
      :else [(hint-name slot) identity])))

(def ^:private number-kinds #{:int :long :short :byte :double :float :char :bool})

(defn- ret-jvm-name [m]
  (case (:kind m)
    :set "void"
    :java (:ret-jvm m)
    (:return (meta/desc-types (:desc (:jvm m))))))

(defn- member-text
  "The member as an error says it: the kt/reify member `Gen9.fn1`, with its Kotlin type."
  [m]
  (str "the kt/reify member `" (simple-name (:iface m)) "." (str/replace (:key m) #"^\." "") "`"
       (when-let [t (:ret m)] (str " (" (meta/type-text t) ")"))))

(defn- java-sam?
  "Is the JVM class `jt` an interface with one abstract method (`Runnable`, `java.util.function.Supplier`)?"
  [^String jt]
  (boolean (when-let [^Class c (r/jvm-class jt)] (and (.isInterface c) (r/sam-of jt)))))

(defn- convert-form
  "The form that converts the value in the local `r` to what the JVM method of `m` returns (as function adapters do), or
  `r` itself when nothing is converted."
  [m r]
  (let [jt (ret-jvm-name m)]
    (case (:kind m)
      :set `(do ~r nil)
      :java (cond (= "void" jt) `(do ~r nil)
                  (r/jvm-descriptor jt) `(ckway.rt/->kotlin ~(r/jvm-descriptor jt) ~r)
                  ;; a Java single-method interface: a Clojure function is adapted, as at a parameter (nil is a value: a
                  ;; Java type says nothing about null)
                  (java-sam? jt) `(if (nil? ~r) nil ~(first (r/adapter-form (r/fi-spec jt jt) jt r)))
                  :else r)
      (let [t (:ret m)
            td (r/type-descriptor t)
            vc (when-not (:suspend? m) (r/vc-conv t jt))]
        (cond
          vc (r/unbox-form (assoc vc :name "result" :result? true) r)
          (#{:fn :fi} (:k td))
          (let [iface (if (:fn-type t)
                        (str "kotlin.jvm.functions.Function" (cond-> (:arity td) (:suspend? td) inc))
                        (:class td))]
            ;; nil is a value only for a nullable type; a value that is no function is a kt error (`ckway.rt/adapt?`)
            `(if (nil? ~r)
               (ckway.rt/nil-result ~(boolean (:nullable? td)) ~(:text td (meta/type-text t)))
               ~(first (r/adapter-form (r/adapter-spec t iface (:signature m)) iface r))))
          (= :unit (:k td)) `(do ~r kotlin.Unit/INSTANCE)
          (number-kinds (:k td)) `(ckway.rt/->kotlin ~td ~r)
          (r/check-result? td (:suspend? m)) `(ckway.rt/->kotlin ~td ~r)
          :else r)))))

(defn- result-form
  "The form that converts the value of `body` to what the JVM method of `m` returns (as function adapters do). A value
  that cannot be the declared type is a kt error that names the member (`ckway.rt/result-error`), at the point of return."
  [m body]
  (let [r (gensym "r")
        conv (convert-form m r)]
    (cond
      (= conv r) body
      (or (= :set (:kind m)) (and (= :java (:kind m)) (= "void" (ret-jvm-name m)))) `(do ~body nil)
      (and (:ret m) (= :unit (:k (r/type-descriptor (:ret m))))) `(do ~body kotlin.Unit/INSTANCE)
      :else `(let [~r (clojure.core/identity ~body)]
               (try ~conv
                    (catch clojure.lang.ExceptionInfo e#
                      (throw (ckway.rt/result-error e# ~(member-text m)))))))))

(defn- bind-symbol
  "The user's parameter symbol with the Kotlin type as a hint when the user wrote none. A primitive hint
  of the user is the boxed class (the body gets objects)."
  [p hint]
  (let [tag (:tag (meta p))]
    (cond
      (and tag (symbol? tag) (#{'int 'long 'short 'byte 'double 'float 'char 'boolean} tag))
      (vary-meta p assoc :tag (symbol (.getName (r/box-class ^Class (r/tag->class *ns* tag)))))
      tag p
      hint (r/lib-tag p hint)
      :else p)))

(defn- member-fn
  "The Clojure function for the written form `w` of member `m`. It takes `this`, the raw JVM arguments
  (boxed) and for a suspend member the continuation last."
  [{:keys [params body member name] :as w} cname frame]
  (let [m member
        raw (vec (repeatedly (count params) #(gensym "raw")))
        k (gensym "k")
        ins (map slot-in (:slots m))
        bindings (vec (concat [(bind-symbol (first params) cname) (first raw)]
                              (mapcat (fn [p [hint conv] r] [(bind-symbol p hint) (conv r)]) (rest params) ins (rest raw))))
        result (result-form m (if (= 1 (count body)) (first body) `(do ~@body)))
        fname (symbol (str/replace (str (simple-name (:iface m)) "_" name) #"[^A-Za-z0-9_]" "_"))]
    (if (:suspend? m)
      `(fn* ~fname [~@raw ~k] (ckway.co/run-body ~k ~frame (fn* [] (let ~bindings ~result))))
      `(fn* ~fname [~@raw] (let ~bindings ~result)))))

;; ---------------------------------------------------------------- annotations

(defn- element-value [^Class ac ^String n x]
  (let [^Method am (try (.getMethod ac n (make-array Class 0))
                        (catch NoSuchMethodException _
                          (fail (str "kt/reify: the annotation " (.getName ac) " has no element `" n "`."))))
        scalar (fn scalar [^Class t v]
                 (let [bad #(fail (str "kt/reify: element `" n "` of " (.getName ac) " takes " (.getSimpleName t) ", got " (r/short-pr v)))]
                   (cond
                     (= String t) (if (string? v) v (bad))
                     (= Boolean/TYPE t) (if (boolean? v) v (bad))
                     (= Character/TYPE t) (if (char? v) v (bad))
                     (.isPrimitive t) (if (number? v)
                                        (condp = t
                                          Integer/TYPE (int v) Long/TYPE (long v) Short/TYPE (short v) Byte/TYPE (byte v)
                                          Float/TYPE (float v) Double/TYPE (double v))
                                        (bad))
                     :else (fail (str "kt/reify: element `" n "` of " (.getName ac) " has the type " (.getSimpleName t)
                                      ", which kt/reify does not support (strings, numbers, booleans, chars and arrays of them)")))))
        rt (.getReturnType am)]
    (if (.isArray rt)
      (vec (map #(scalar (.getComponentType rt) %) (if (sequential? x) x [x])))
      (scalar rt x))))

(defn annotations-of
  "[{:class :elements}] from the metadata of the member name symbol."
  [name-sym]
  (vec (for [[k v] (sort-by (comp str key) (r/annotation-meta name-sym))
             :let [^Class ac (r/tag->class *ns* k)
                   elems (cond (or (true? v) (nil? v) (and (map? v) (empty? v))) {}
                               (map? v) (into {} (for [[n x] v] [(clojure.core/name n) x]))
                               :else {"value" v})]]
         {:class (.getName ac)
          :elements (into (sorted-map) (for [[n x] elems] [n (element-value ac n x)]))})))

;; ---------------------------------------------------------------- one written form

(defn- parse-member [form]
  (let [[nm params & body] form]
    (when-not (and (symbol? nm) (vector? params))
      (fail (str "kt/reify: a member is (name [this ...] body...), got " (r/short-pr form))))
    (when (empty? params) (fail (str "kt/reify: `" nm "` needs `this` as its first parameter: (" nm " [this ...] ...)")))
    (when-not (every? symbol? params)
      (fail (str "kt/reify: the parameters of `" nm "` must be plain symbols (no destructuring, no `&`), got " (r/short-pr params))))
    (when (some #{'&} params)
      (fail (str "kt/reify: `&` is not allowed in the parameters of `" nm "`: they must be plain symbols")))
    {:name nm :params params :body body :argc (count params)
     :hints (mapv #(some->> (:tag (meta %)) (r/tag->class *ns*)) (rest params))
     :annotations (annotations-of nm)}))

(defn- default-impls
  "The static method in `I$DefaultImpls` that holds the body of the abstract JVM method `m` of `c`, or nil."
  ^Method [^Class c ^Method m]
  (when-let [^Class impls (r/jvm-class (str (.getName c) "$DefaultImpls"))]
    (let [want (vec (cons c (.getParameterTypes m)))]
      (first (for [^Method s (.getDeclaredMethods impls)
                   :when (and (= (.getName m) (.getName s)) (Modifier/isStatic (.getModifiers s))
                              (= want (vec (.getParameterTypes s))) (= (.getReturnType m) (.getReturnType s)))]
               s)))))

(defn- bridge-convs
  "{:arg-vcs [binary-name-or-nil ...] :ret-vc binary-name-or-nil}: where the more specific method `m` takes or returns
  the underlying value of a value class, a bridge method that has the erased type unboxes the argument and boxes the
  result."
  [m]
  (when m
    {:arg-vcs (mapv #(some-> (r/vc-conv (:type %) (:jvm-type %)) :vc :class) (:slots m))
     :ret-vc (when (and (#{:fn :get} (:kind m)) (not (:suspend? m)))
               (some-> (r/vc-conv (:ret m) (ret-jvm-name m)) :vc :class))}))

(defn- class-methods
  "The methods of the generated class, written ones first in the written order."
  [written jvm members]
  (let [by-key (into {} (map (fn [w] [[(:name (:jvm (:member w))) (:desc (:jvm (:member w)))] w]) written))
        sig-of (fn [[n d] ^Class c] (or (some #(when (= [n d] [(:name (:jvm %)) (:desc (:jvm %))]) (:signature %)) members)
                                        (str (.getName c) "." n d)))]
    (doseq [[[n d :as k] {:keys [conflict class]}] jvm
            :when (and conflict (not (by-key k)))]
      (let [m (first (filter #(= [n d] [(:name (:jvm %)) (:desc (:jvm %))]) members))]
        (fail (str "kt/reify: the member `" (if m (:key m) n) "` has a default body in two unrelated interfaces ("
                   (str/join " and " (map #(.getName ^Class %) conflict))
                   "), so the JVM cannot choose one (IncompatibleClassChangeError: Conflicting default methods). Write it yourself"
                   (when m (str ": " (written-form m) "  " (:signature m))) "."))))
    (concat
     (for [w written
           :let [j (:jvm (:member w))]]
       {:impl :fn :name (:name j) :desc (:desc j) :idx (:idx w) :annotations (:annotations w)})
     (for [[[n d :as k] {:keys [abstract? class method bridge-to]}] (sort-by key jvm)
           :when (and abstract? (not (by-key k)))]
       (cond
         bridge-to (merge {:impl :bridge :name n :desc d :target-name (first bridge-to) :target-desc (second bridge-to)}
                          (bridge-convs (first (filter #(= bridge-to (jvm-key %)) members))))
         :else
         (if-let [s (default-impls class method)]
           {:impl :delegate :name n :desc d :impls (.getName (.getDeclaringClass s)) :impls-desc (desc-of s)}
           {:impl :abstract :name n :desc d
            :message (str "kt/reify: the abstract member `" (sig-of k class) "` was called, but the kt/reify form does not write it")}))))))

(defn- serve-siblings
  "`written` with one more entry for each leaf override that a written form can serve as well. The interfaces of one
  `kt/reify` can override one member in different ways (`S1.get(): CharSequence`, `S2.get(): Comparable<*>` over
  `Src.get(): Any`): a JVM method for each. The form that is written for one is the body of the others too, with the
  result checked against the result type of each (a kt error when it does not fit), unless the user writes that member
  too. When the leaves differ in their PARAMETER types one body cannot serve them: a kt error that says so."
  [written members leaf-groups jvm]
  (let [explicit (set (map #(jvm-key (:member %)) written))
        extra (reduce
               (fn [{:keys [taken out] :as acc} w]
                 (let [m (:member w) k (jvm-key m)
                       ks (disj (set (mapcat identity (filter #(contains? (set %) k) leaf-groups))) k)
                       ;; the JVM name and the JVM parameter types, not the name that is written, say which methods are the
                       ;; same member: a Java leaf is written `get`, a Kotlin one `.get`
                       same-jvm-name? (fn [m2] (= (:name (:jvm m2)) (:name (:jvm m))))
                       same-params? (fn [m2] (= (mapv :jvm-type (:slots m2)) (mapv :jvm-type (:slots m))))
                       sibs (for [m2 members
                                  :when (and (not (explicit (jvm-key m2))) (not (taken (jvm-key m2)))
                                             (not= (jvm-key m2) k)
                                             (or
                                              ;; a leaf override of the same member (a Kotlin name key, or the JVM name of a Java leaf)
                                              (and (contains? ks (jvm-key m2))
                                                   (or (and (= (:kind m2) (:kind m)) (= (:key m2) (:key m)))
                                                       (same-jvm-name? m2)))
                                              ;; an abstract method of another interface with the same JVM name and parameters, that
                                              ;; differs only in the result type (a Java interface that does not extend the Kotlin one)
                                              (and (:abstract? (get jvm (jvm-key m2)))
                                                   (contains? #{:fn :get :java} (:kind m2)) (contains? #{:fn :get :java} (:kind m))
                                                   (same-jvm-name? m2) (same-params? m2))))]
                              m2)]
                   (doseq [m2 sibs
                           :when (not= (mapv :jvm-type (:slots m2)) (mapv :jvm-type (:slots m)))]
                     (fail (str "kt/reify: `" (:key m) "` is overridden with different parameter types in " (:iface m) " and "
                                (:iface m2) ", so one body cannot serve both:\n    " (:signature m) "\n    " (:signature m2)
                                "\n  Write the member under each interface: (kt/reify " (simple-name (:iface m)) " " (written-form m)
                                " " (simple-name (:iface m2)) " " (written-form m2) ")")))
                   {:taken (into taken (map jvm-key sibs))
                    :out (into out (map #(assoc w :member %) sibs))}))
               {:taken #{} :out []} written)]
    (vec (map-indexed (fn [i w] (assoc w :idx i)) (concat written (:out extra))))))

(defn expand
  "Expansion of `(kt/reify spec...)` (see the namespace docstring)."
  [specs]
  (let [sections (parse-sections specs)
        classes (vec (distinct (map :class sections)))
        chain (interface-chain classes)
        jvm (jvm-methods chain)
        members (members-of chain jvm)
        written (vec (map-indexed
                      (fn [i [sec form]]
                        (let [w (parse-member form)
                              names (set (map #(.getName ^Class %) (interface-chain [(:class sec)])))
                              m (pick-member members chain names w)]
                          (when (> (+ (:argc w) (if (:suspend? m) 1 0)) 20)
                            (fail (str "kt/reify: `" (:name w) "` has more than 20 parameters (with `this`): not supported")))
                          (assoc w :member m :idx i)))
                      (for [sec sections, form (:forms sec)] [sec form])))
        _ (doseq [[k ws] (group-by #(let [j (:jvm (:member %))] [(:name j) (:desc j)]) written)
                  :when (> (count ws) 1)]
            (fail (str "kt/reify: the member `" (:key (:member (first ws))) "` is written twice (" (str/join ", " (map #(r/short-pr (list (:name %) (vec (:params %)))) ws)) ")")))
        written (serve-siblings written members (vals (bridge-leaves chain)) jvm)
        spec {:ifaces (mapv #(.getName ^Class %) classes) :iface-classes classes :methods (vec (class-methods written jvm members))}
        cname (bridge/reify-class (simple-name (.getName ^Class (first classes))) spec)
        frame (gensym "frame")
        fns (mapv #(member-fn % cname frame) written)]
    `(new ~(symbol cname)
          ~(if (some #(:suspend? (:member %)) written)
             `(let [~frame (ckway.co/capture-frame)] (object-array [~@fns]))
             `(object-array [~@fns]))
          nil)))

(defn form-info
  "Compile-time class of a `(kt/reify ...)` form (`ckway.resolve/form-info`): the generated class, which is
  a subtype of every interface of the form. nil when the form has an error (the expansion reports it)."
  [form]
  (try
    (let [x (macroexpand-1 form)]
      (when (and (seq? x) (= 'new (first x)))
        (r/jvm-class (str (second x)))))
    (catch clojure.lang.ExceptionInfo e
      (if (:kt/error (ex-data e)) nil (throw e)))))
